SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_AF_DATA;
DROP TYPE PAL_T_AF_SEED;
DROP TYPE PAL_T_AF_PARAMS;
DROP TYPE PAL_T_AF_RESULTS;
DROP TABLE PAL_AF_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_AF');
DROP VIEW V_AF_DATA;
DROP TABLE AF_SEED;
DROP TABLE AF_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_AF_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_AF_SEED AS TABLE (ID INTEGER, SEED INTEGER);
CREATE TYPE PAL_T_AF_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_AF_RESULTS AS TABLE (ID INTEGER, CLUSTER_NUMBER INTEGER);

CREATE COLUMN TABLE PAL_AF_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_AF_SIGNATURE VALUES (1, 'PAL.PAL_T_AF_DATA', 'in');
INSERT INTO PAL_AF_SIGNATURE VALUES (2, 'PAL.PAL_T_AF_SEED', 'in');
INSERT INTO PAL_AF_SIGNATURE VALUES (3, 'PAL.PAL_T_AF_PARAMS', 'in');
INSERT INTO PAL_AF_SIGNATURE VALUES (4, 'PAL.PAL_T_AF_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_AF', 'AFLPAL', 'AP', PAL_AF_SIGNATURE);

-- app setup
CREATE VIEW V_AF_DATA AS 
	SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE AF_SEED LIKE PAL_T_AF_SEED;
CREATE COLUMN TABLE AF_RESULTS LIKE PAL_T_AF_RESULTS;

-- app runtime
DROP TABLE #AF_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #AF_PARAMS LIKE PAL_T_AF_PARAMS;
INSERT INTO #AF_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #AF_PARAMS VALUES ('CLUSTER_NUMBER', 0, null, null);
-- Distance: 1:Manhattan, 2:Euclidean, 3:Minkowski, 4:Chebyshev, 5: Standardized Euclidian, 6: Cosine
INSERT INTO #AF_PARAMS VALUES ('DISTANCE_METHOD', 2, null, null); 
--INSERT INTO #AF_PARAMS VALUES ('MINKOW_P', 3, null, null); -- with Minkowski
--INSERT INTO #AF_PARAMS VALUES ('MAX_ITERATION', 500, null, null); 
--INSERT INTO #AF_PARAMS VALUES ('CON_ITERATION', 100, null, null); 

TRUNCATE TABLE AF_RESULTS;

CALL _SYS_AFL.PAL_AF (V_AF_DATA, AF_SEED, #AF_PARAMS, AF_RESULTS) WITH OVERVIEW;

SELECT * FROM V_AF_DATA;
SELECT * FROM AF_SEED;
SELECT * FROM AF_RESULTS;
SELECT a.ID, b.CUSTOMER, b.LIFESPEND, b.NEWSPEND, b.INCOME, b.LOYALTY, CLUSTER_NUMBER + 1 AS CLUSTER_NUMBER
	FROM AF_RESULTS a, CUSTOMERS b 
	WHERE a.ID = b.ID
	;
