-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_MATRIX";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_CM');
DROP TABLE "DATA";
DROP TABLE "MATRIX";
DROP TABLE "RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "ORIGINAL" VARCHAR(10), "PREDICTED" VARCHAR(10));
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR (100));
CREATE TYPE "T_MATRIX" AS TABLE ("ID" VARCHAR(100), "CLASS1" INTEGER, "CLASS2" INTEGER);
CREATE TYPE "T_RESULTS" AS TABLE ("ID" VARCHAR(100), "RECALL" DOUBLE, "PRECISION" DOUBLE, "FMEASURE" DOUBLE, "SUPPORT" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_MATRIX', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_RESULTS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'CONFUSIONMATRIX', 'DEVUSER', 'P_CM', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 'Cat', 'Cat');
INSERT INTO "DATA" VALUES (2, 'Cat', 'Cat');
INSERT INTO "DATA" VALUES (3, 'Cat', 'Cat');
INSERT INTO "DATA" VALUES (4, 'Cat', 'Dog');
INSERT INTO "DATA" VALUES (5, 'Cat', 'Cat');
INSERT INTO "DATA" VALUES (6, 'Dog', 'Dog');
INSERT INTO "DATA" VALUES (7, 'Dog', 'Cat');
INSERT INTO "DATA" VALUES (8, 'Dog', 'Dog');
INSERT INTO "DATA" VALUES (9, 'Cat', 'Dog');
INSERT INTO "DATA" VALUES (10, 'Dog', 'Dog');

CREATE COLUMN TABLE "MATRIX" LIKE "T_MATRIX";
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('BETA', null, 1, null);

TRUNCATE TABLE "MATRIX";
TRUNCATE TABLE "RESULTS";

CALL "P_CM" ("DATA", "#PARAMS", "MATRIX", "RESULTS") WITH OVERVIEW;

SELECT * FROM "DATA";
SELECT * FROM "MATRIX";
SELECT * FROM "RESULTS";
