SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_DB_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_DB_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_DB_RESULTS AS TABLE (ID INTEGER, CLUSTER_NUMBER INTEGER);

CREATE COLUMN TABLE PAL_DB_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_DB_SIGNATURE VALUES (1, 'PAL.PAL_T_DB_DATA', 'in');
INSERT INTO PAL_DB_SIGNATURE VALUES (2, 'PAL.PAL_T_DB_PARAMS', 'in');
INSERT INTO PAL_DB_SIGNATURE VALUES (3, 'PAL.PAL_T_DB_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_DB', 'AFLPAL', 'DBSCAN', PAL_DB_SIGNATURE);

-- app setup

CREATE VIEW V_DB_DATA AS 
	SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY 
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE DB_PARAMS LIKE PAL_T_DB_PARAMS;
CREATE COLUMN TABLE DB_RESULTS LIKE PAL_T_DB_RESULTS;

CREATE VIEW V_DB_RESULTS AS
	SELECT a.ID, b.CUSTOMER, b.LIFESPEND, b.NEWSPEND, b.INCOME, b.LOYALTY, a.CLUSTER_NUMBER
		FROM DB_RESULTS a, CUSTOMERS b 
		WHERE a.ID = b.ID
	;

INSERT INTO DB_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO DB_PARAMS VALUES ('DISTANCE_METHOD', 1, null, null); -- 1. Manhattan, 2. Euclidian, 3. Minkowski
INSERT INTO DB_PARAMS VALUES ('AUTO_PARAM', null, null, 'true');
--INSERT INTO DB_PARAMS VALUES ('MINPTS', 10, null, null);
--INSERT INTO DB_PARAMS VALUES ('RADIUS', null, 0.0, null);
--INSERT INTO DB_PARAMS VALUES ('MINKOW_P', 0, null, null);

-- app runtime

--UPDATE DB_PARAMS SET INTARGS=4 WHERE NAME='THREAD_NUMBER';
--UPDATE DB_PARAMS SET STRINGARGS='false' WHERE NAME='AUTO_PARAM';

TRUNCATE TABLE DB_RESULTS;

CALL _SYS_AFL.PAL_DB (V_DB_DATA, DB_PARAMS, DB_RESULTS) WITH OVERVIEW;
