SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_MV_DATA;
DROP TYPE PAL_T_MV_PARAMS;
DROP TYPE PAL_T_MV_RESULTS;
DROP TYPE PAL_T_MV_RESULTS_INFO;
DROP TABLE PAL_MV_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_MV');
DROP TABLE MV_RESULTS;
DROP TABLE MV_RESULTS_INFO;

-- PAL setup
CREATE TYPE PAL_T_MV_DATA AS TABLE (ID INTEGER, POLICY NVARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION NVARCHAR(10), FRAUD NVARCHAR(10));
CREATE TYPE PAL_T_MV_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_MV_RESULTS AS TABLE (ID INTEGER, POLICY NVARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION NVARCHAR(10), FRAUD NVARCHAR(10));
CREATE TYPE PAL_T_MV_RESULTS_INFO AS TABLE (NAME VARCHAR(10), VALUE VARCHAR(10), HITS INTEGER);

CREATE COLUMN TABLE PAL_MV_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_MV_SIGNATURE VALUES (1, 'PAL.PAL_T_MV_DATA', 'in');
INSERT INTO PAL_MV_SIGNATURE VALUES (2, 'PAL.PAL_T_MV_PARAMS', 'in');
INSERT INTO PAL_MV_SIGNATURE VALUES (3, 'PAL.PAL_T_MV_RESULTS', 'out');
INSERT INTO PAL_MV_SIGNATURE VALUES (4, 'PAL.PAL_T_MV_RESULTS_INFO', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_MV', 'AFLPAL', 'SUBSTITUTE_MISSING_VALUES', PAL_MV_SIGNATURE);

-- app setup
CREATE COLUMN TABLE MV_RESULTS LIKE PAL_T_MV_RESULTS;
CREATE COLUMN TABLE MV_RESULTS_INFO LIKE PAL_T_MV_RESULTS_INFO;

-- app runtime
DROP TABLE #MV_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #MV_PARAMS LIKE PAL_T_MV_PARAMS;
INSERT INTO #MV_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
-- for each column - 100:Mode, 200:Mean; 201:Median
INSERT INTO #MV_PARAMS VALUES ('ID', 100, null, null); 			
INSERT INTO #MV_PARAMS VALUES ('POLICY', 100, null, null); 			
INSERT INTO #MV_PARAMS VALUES ('AGE', 201, null, null);
INSERT INTO #MV_PARAMS VALUES ('AMOUNT', 200, null, null);
INSERT INTO #MV_PARAMS VALUES ('OCCUPATION', 100, null, null); 			
INSERT INTO #MV_PARAMS VALUES ('FRAUD', 100, null, null); 			

TRUNCATE TABLE MV_RESULTS;
TRUNCATE TABLE MV_RESULTS_INFO;

CALL _SYS_AFL.PAL_MV (CLAIMS_MV, #MV_PARAMS, MV_RESULTS, MV_RESULTS_INFO) WITH OVERVIEW;

SELECT * FROM CLAIMS_MV;
SELECT * FROM MV_RESULTS;
SELECT * FROM MV_RESULTS_INFO;

