SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_AD_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_AD_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));

CREATE COLUMN TABLE PAL_AD_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_AD_SIGNATURE VALUES (1, 'PAL.PAL_T_AD_DATA', 'in');
INSERT INTO PAL_AD_SIGNATURE VALUES (2, 'PAL.PAL_T_AD_PARAMS', 'in');
INSERT INTO PAL_AD_SIGNATURE VALUES (3, 'PAL.PAL_T_AD_DATA', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_AD', 'AFLPAL', 'ANOMALYDETECTION', PAL_AD_SIGNATURE);

-- app setup

CREATE VIEW V_AD_DATA AS 
	SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY 
		FROM CUSTOMERS_AD
	;
CREATE COLUMN TABLE AD_PARAMS LIKE PAL_T_AD_PARAMS;
CREATE COLUMN TABLE AD_RESULTS LIKE PAL_T_AD_DATA;

INSERT INTO AD_PARAMS VALUES ('GROUP_NUMBER', 3, null, null);
INSERT INTO AD_PARAMS VALUES ('DISTANCE_LEVEL', 2, null, null);
INSERT INTO AD_PARAMS VALUES ('OUTLIER_PERCENTAGE', null, 0.01, null);
INSERT INTO AD_PARAMS VALUES ('OUTLIER_DEFINE', 1, null, null);
INSERT INTO AD_PARAMS VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO AD_PARAMS VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO AD_PARAMS VALUES ('NORMALIZATION', 0, null, null);
INSERT INTO AD_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO AD_PARAMS VALUES ('EXIT_THRESHOLD', null, 0.0001, null);

-- app runtime

UPDATE AD_PARAMS SET DOUBLEARGS=0.01 WHERE NAME='OUTLIER_PERCENTAGE';
UPDATE AD_PARAMS SET INTARGS=1 WHERE NAME='OUTLIER_DEFINE';

TRUNCATE TABLE AD_RESULTS;

CALL _SYS_AFL.PAL_AD (V_AD_DATA, AD_PARAMS, AD_RESULTS) WITH OVERVIEW;

SELECT * FROM AD_RESULTS;

