-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_FRM_P');
DROP TABLE "Data";
DROP TABLE "DataUsers";
DROP TABLE "DataAlbums";
DROP TABLE "Results";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("id" INTEGER, "user" NVARCHAR(255), "album" NVARCHAR(255));
CREATE TYPE "T_RESULTS" AS TABLE ("id" INTEGER, "user" NVARCHAR(255), "album" NVARCHAR(255), "predictedRating" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_USERS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_ALBUMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_MODEL_METADATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_MODEL', 'IN');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_MODEL_FACTORS', 'IN');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (8, 'DEVUSER', 'T_RESULTS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'FRMPREDICT', 'DEVUSER', 'P_FRM_P', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "Data" LIKE "T_DATA";
CREATE COLUMN TABLE "DataUsers" LIKE "T_USERS";
CREATE COLUMN TABLE "DataAlbums" LIKE "T_ALBUMS";
CREATE COLUMN TABLE "Results" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 1, null, null); -- default: 1

TRUNCATE TABLE "Data";
INSERT INTO "Data" VALUES (1,'Joe','Like A Virgin');
INSERT INTO "Data" VALUES (2,'Julie','Wish You Were Here');

TRUNCATE TABLE "DataUsers";
TRUNCATE TABLE "DataAlbums";
INSERT INTO "DataAlbums" VALUES ('Like A Virgin','Madonna',1984,'Pop,Dance',15,25);
INSERT INTO "DataAlbums" VALUES ('Wish You Were Here','Pink Floyd',1975,'Progressive rock',10,13);

TRUNCATE TABLE "Results";

CALL "P_FRM_P" ("Data", "DataUsers", "DataAlbums", "ModelMetadata", "Model", "ModelFactors", "#PARAMS", "Results") WITH OVERVIEW;

SELECT * FROM "Results";
