SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_ABC_DATA AS TABLE (CUSTOMER VARCHAR(60), LIFESPEND DOUBLE);
CREATE TYPE PAL_T_ABC_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_ABC_RESULTS AS TABLE (ABC VARCHAR(60), CUSTOMER VARCHAR(60));

CREATE COLUMN TABLE PAL_ABC_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_ABC_SIGNATURE VALUES (1, 'PAL.PAL_T_ABC_DATA', 'in');
INSERT INTO PAL_ABC_SIGNATURE VALUES (2, 'PAL.PAL_T_ABC_PARAMS', 'in');
INSERT INTO PAL_ABC_SIGNATURE VALUES (3, 'PAL.PAL_T_ABC_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_ABC', 'AFLPAL', 'ABC', PAL_ABC_SIGNATURE);

-- app setup

CREATE VIEW V_ABC_DATA AS 
	SELECT CUSTOMER, LIFESPEND
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE ABC_PARAMS LIKE PAL_T_ABC_PARAMS;
CREATE COLUMN TABLE ABC_RESULTS LIKE PAL_T_ABC_RESULTS;

INSERT INTO ABC_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO ABC_PARAMS VALUES ('PERCENT_A', null, 0.1, null);
INSERT INTO ABC_PARAMS VALUES ('PERCENT_B', null, 0.2, null);
INSERT INTO ABC_PARAMS VALUES ('PERCENT_C', null, 0.7, null);

-- app runtime

UPDATE ABC_PARAMS SET DOUBLEARGS=0.05 WHERE NAME='PERCENT_A';
UPDATE ABC_PARAMS SET DOUBLEARGS=0.15 WHERE NAME='PERCENT_B';
UPDATE ABC_PARAMS SET DOUBLEARGS=0.8 WHERE NAME='PERCENT_C';

TRUNCATE TABLE ABC_RESULTS;

CALL _SYS_AFL.PAL_ABC (V_ABC_DATA, ABC_PARAMS, ABC_RESULTS) WITH OVERVIEW;


