-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_INIT";
DROP TYPE "T_RESULTS";
DROP TYPE "T_MODELS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_GMM');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP TABLE "MODELS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "LIFESPEND" DOUBLE, "NEWSPEND" DOUBLE, "INCOME" DOUBLE, "LOYALTY" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_INIT" AS TABLE ("ID" INTEGER, "CLUSTER" INTEGER);
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "CLUSTER" INTEGER, "PROB_1" DOUBLE, "PROB_2" DOUBLE);
CREATE TYPE "T_MODELS" AS TABLE ("MODEL_1" DOUBLE, "MODEL_2" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_INIT', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_MODELS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'GMM', 'DEVUSER', 'P_GMM', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "ID", "LIFESPEND", "NEWSPEND", "INCOME", "LOYALTY"
		FROM "PAL"."CUSTOMERS"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "MODELS" LIKE "T_MODELS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('INIT_MODE', 0, null, null); -- 0: # distributions; 1: seed data
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO "#PARAMS" VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO "#PARAMS" VALUES ('ERROR_TOL', null, 0.01, null);

DROP TABLE "#INIT";
CREATE LOCAL TEMPORARY COLUMN TABLE "#INIT" LIKE "T_INIT";
INSERT INTO "#INIT" VALUES (0, 2);

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "MODELS";

CALL "P_GMM" ("V_DATA", "#PARAMS", "#INIT", "RESULTS", "MODELS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "MODELS";
