-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_RANDOM";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_ST');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP TABLE "RANDOM";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("CALENDAR_ID" INTEGER, "SALES_AMOUNT" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("CYCLE_LENGTH" INTEGER, "SEASONALITY_MODE" VARCHAR(60));
CREATE TYPE "T_RANDOM" AS TABLE ("ID" INTEGER, "VALUE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_RANDOM', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'SEASONALITYTEST', 'DEVUSER', 'P_ST', "SIGNATURE");

-- data setup
CREATE VIEW "V_DATA" AS 
	SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		FROM "PAL"."ORDER_FACTS"
		WHERE "ITEM_ID" BETWEEN 0 AND 9
		GROUP BY "CALENDAR_ID" 
		ORDER BY "CALENDAR_ID"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "RANDOM" LIKE "T_RANDOM";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.2, null); -- Threshold for auto-correlation coefficient

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "RANDOM";

CALL "P_ST" ("V_DATA", "#PARAMS", "RESULTS", "RANDOM") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "RANDOM";
