SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_VE_DATA1;
DROP TYPE PAL_T_VE_DATA2;
DROP TYPE PAL_T_VE_PARAMS;
DROP TYPE PAL_T_VE_RESULTS_INFO;
DROP TABLE PAL_VE_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_VE');
DROP TABLE VE_DATA1;
DROP TABLE VE_DATA2;
DROP TABLE VE_RESULTS_INFO;

-- PAL setup
CREATE TYPE PAL_T_VE_DATA1 AS TABLE (X INTEGER);
CREATE TYPE PAL_T_VE_DATA2 AS TABLE (Y INTEGER);
CREATE TYPE PAL_T_VE_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_VE_RESULTS_INFO AS TABLE (NAME VARCHAR(100), VALUE DOUBLE);

CREATE COLUMN TABLE PAL_VE_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_VE_SIGNATURE VALUES (1, 'PAL.PAL_T_VE_DATA1', 'in');
INSERT INTO PAL_VE_SIGNATURE VALUES (2, 'PAL.PAL_T_VE_DATA2', 'in');
INSERT INTO PAL_VE_SIGNATURE VALUES (3, 'PAL.PAL_T_VE_PARAMS', 'in');
INSERT INTO PAL_VE_SIGNATURE VALUES (4, 'PAL.PAL_T_VE_RESULTS_INFO', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_VE', 'AFLPAL', 'VAREQUALTEST', PAL_VE_SIGNATURE);

-- app setup
CREATE COLUMN TABLE VE_DATA1 LIKE PAL_T_VE_DATA1;
INSERT INTO VE_DATA1 VALUES (1);
INSERT INTO VE_DATA1 VALUES (2);
INSERT INTO VE_DATA1 VALUES (4);
INSERT INTO VE_DATA1 VALUES (7);
INSERT INTO VE_DATA1 VALUES (3);
CREATE COLUMN TABLE VE_DATA2 LIKE PAL_T_VE_DATA2;
INSERT INTO VE_DATA2 VALUES (10);
INSERT INTO VE_DATA2 VALUES (15);
INSERT INTO VE_DATA2 VALUES (12);
CREATE COLUMN TABLE VE_RESULTS_INFO LIKE PAL_T_VE_RESULTS_INFO;

-- app runtime
DROP TABLE #VE_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #VE_PARAMS LIKE PAL_T_VE_PARAMS;
INSERT INTO #VE_PARAMS VALUES ('TEST_TYPE', 0, null, null); -- 0:Two side, 1:Less, 2:Greater
TRUNCATE TABLE VE_RESULTS_INFO;

CALL _SYS_AFL.PAL_VE (VE_DATA1, VE_DATA2, #VE_PARAMS, VE_RESULTS_INFO) WITH OVERVIEW;

SELECT * FROM VE_DATA1;
SELECT * FROM VE_DATA2;
SELECT * FROM VE_RESULTS_INFO;
