SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_TS_DATA AS TABLE (CALENDAR_ID INT, SALES_AMOUNT DOUBLE);
CREATE TYPE PAL_T_TS_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_TS_RESULTS AS TABLE (CALENDAR_ID INT, SALES_AMOUNT DOUBLE);

CREATE COLUMN TABLE PAL_TS_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_TS_SIGNATURE VALUES (1, 'PAL.PAL_T_TS_DATA', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (2, 'PAL.PAL_T_TS_PARAMS', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (3, 'PAL.PAL_T_TS_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_TS_S', 'AFLPAL', 'SINGLESMOOTH', PAL_TS_SIGNATURE);

-- app setup

CREATE VIEW V_TS_DATA AS 
	SELECT CALENDAR_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT 
		FROM ORDER_FACTS 
		GROUP BY CALENDAR_ID 
		ORDER BY CALENDAR_ID
	;

-- app runtime

DROP TABLE #TS_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #TS_PARAMS LIKE PAL_T_TS_PARAMS;
INSERT INTO #TS_PARAMS VALUES ('RAW_DATA_COL' ,1, null, null);
INSERT INTO #TS_PARAMS VALUES ('ALPHA', null, 0.3, null);
INSERT INTO #TS_PARAMS VALUES ('STARTTIME', 0, null, null);

DROP TABLE #TS_RESULTS;
CREATE LOCAL TEMPORARY COLUMN TABLE #TS_RESULTS LIKE _SYS_AFL.PAL_T_TS_RESULTS;

CALL _SYS_AFL.PAL_TS_S (V_TS_DATA, #TS_PARAMS, #TS_RESULTS) WITH OVERVIEW;

SELECT * FROM #TS_RESULTS;

