-- cleanup
DROP TYPE "T_RATINGS";
DROP TYPE "T_USERS";
DROP TYPE "T_ALBUMS";
DROP TYPE "T_PARAMS";
DROP TYPE "T_MODEL_METADATA";
DROP TYPE "T_MODEL";
DROP TYPE "T_MODEL_FACTORS";
DROP TYPE "T_ITERATION_INFO";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_FRM_T');
DROP TABLE "ModelMetadata";
DROP TABLE "Model";
DROP TABLE "ModelFactors";
DROP TABLE "IterationInfo";

-- procedure setup
CREATE TYPE "T_RATINGS" AS TABLE ("user" NVARCHAR(255), "album" NVARCHAR(255), "rating" INTEGER);
CREATE TYPE "T_USERS" AS TABLE ("user" NVARCHAR(255), "gender" NVARCHAR(255), "country" NVARCHAR(255), "generation" NVARCHAR(255));
CREATE TYPE "T_ALBUMS" AS TABLE ("album" NVARCHAR(255), "artist" NVARCHAR(255), "released" INTEGER, "genre" NVARCHAR(255), "totalCertifiedCopies" DOUBLE, "claimedSales" INTEGER);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_MODEL_METADATA" AS TABLE ("id" INTEGER, "content" VARCHAR(5000));
CREATE TYPE "T_MODEL" AS TABLE ("id" INTEGER, "map" VARCHAR(255), "weight" DOUBLE);
CREATE TYPE "T_MODEL_FACTORS" AS TABLE ("factorId" INTEGER, "factors" DOUBLE);
CREATE TYPE "T_ITERATION_INFO" AS TABLE ("step" VARCHAR(255), "costFunctionValue" VARCHAR(255), "rootMeanSquareError" VARCHAR(255), "stepSize" VARCHAR(255));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_RATINGS', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_USERS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_ALBUMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_MODEL_METADATA', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_MODEL', 'OUT');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_MODEL_FACTORS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (8, 'DEVUSER', 'T_ITERATION_INFO', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'FRMTRAIN', 'DEVUSER', 'P_FRM_T', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "ModelMetadata" LIKE "T_MODEL_METADATA";
CREATE COLUMN TABLE "Model" LIKE "T_MODEL";
CREATE COLUMN TABLE "ModelFactors" LIKE "T_MODEL_FACTORS";
CREATE COLUMN TABLE "IterationInfo" LIKE "T_ITERATION_INFO";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('METHOD', 3, null, null); -- 0: SGD, 1: MOMENTUM, 2: NAG, 3: ADAGRAD
INSERT INTO "#PARAMS" VALUES ('FACTOR_NUMBER', 2, null, null); -- default: 8
INSERT INTO "#PARAMS" VALUES ('SEED', 0, null, null); -- default: 0 use current time
INSERT INTO "#PARAMS" VALUES ('MAX_ITERATION', 100, null, null); -- default: 50
INSERT INTO "#PARAMS" VALUES ('ITEM_CATEGORY_COL', 2, null, null);

TRUNCATE TABLE "ModelMetadata";
TRUNCATE TABLE "Model";
TRUNCATE TABLE "ModelFactors";
TRUNCATE TABLE "IterationInfo";

CALL "P_FRM_T" ("PAL"."Ratings", "PAL"."RatingsUsers", "PAL"."RatingsAlbums", "#PARAMS", "ModelMetadata", "Model", "ModelFactors", "IterationInfo") WITH OVERVIEW;

SELECT * FROM "ModelMetadata";
SELECT * FROM "Model";
SELECT * FROM "ModelFactors";
SELECT * FROM "IterationInfo";
