-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_OUTLIERS";
DROP TYPE "T_STATS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_GRUBBS');
DROP TABLE "DATA";
DROP TABLE "OUTLIERS";
DROP TABLE "STATS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "VALUE" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_OUTLIERS" AS TABLE ("ID" INTEGER, "OUTLIER_ID" INTEGER, "OUTLIER_VALUE" DOUBLE);
CREATE TYPE "T_STATS" AS TABLE ("ID" INTEGER, "NAME" VARCHAR(60), "VALUE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(256), "TYPE_NAME" VARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_OUTLIERS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_STATS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'GRUBBSTEST', 'DEVUSER', 'P_GRUBBS', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 4.254843);
INSERT INTO "DATA" VALUES (2, 0.135000);
INSERT INTO "DATA" VALUES (3, 11.072257);
INSERT INTO "DATA" VALUES (4, 14.797838);
INSERT INTO "DATA" VALUES (5, 12.125133);
INSERT INTO "DATA" VALUES (6, 14.265839);
INSERT INTO "DATA" VALUES (7, 7.731352);
INSERT INTO "DATA" VALUES (8, 6.856739);
INSERT INTO "DATA" VALUES (9, 15.094403);
INSERT INTO "DATA" VALUES (10, 8.149382);
INSERT INTO "DATA" VALUES (11, 9.160144);

CREATE COLUMN TABLE "OUTLIERS" LIKE "T_OUTLIERS";
CREATE COLUMN TABLE "STATS" LIKE "T_STATS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('METHOD', 2, null, null); -- 1: Two-sided; 2: One-sided Min; 3: One-Sided Max; 4: Repeat Two-sided
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.2, null); -- Significance level (default: 0.05)

TRUNCATE TABLE "OUTLIERS";
TRUNCATE TABLE "STATS";

CALL "P_GRUBBS" ("DATA", "#PARAMS", "OUTLIERS", "STATS") WITH OVERVIEW;

SELECT * FROM "OUTLIERS";
SELECT * FROM "STATS";
