-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_LOADINGS";
DROP TYPE "T_LOADINGS_INFO";
DROP TYPE "T_SCORES";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_PCA');
DROP VIEW "V_DATA";
DROP TABLE "LOADINGS";
DROP TABLE "LOADINGS_INFO";
DROP TABLE "SCORES";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "LIFESPEND" DOUBLE, "NEWSPEND" DOUBLE, "INCOME" DOUBLE, "LOYALTY" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_LOADINGS" AS TABLE("PCID" VARCHAR(50), "LIFESPEND_W" DOUBLE, "NEWSPEND_W" DOUBLE, "INCOME_W" DOUBLE, "LOYALTY_W" DOUBLE);
CREATE TYPE "T_LOADINGS_INFO" AS TABLE("PCID" VARCHAR(50),"STDDEV" DOUBLE, "VARIANCE" DOUBLE, "CUMULATIVE" DOUBLE);
CREATE TYPE "T_SCORES" AS TABLE("ID" INTEGER, "Comp1" DOUBLE, "Comp2" DOUBLE, "Comp3" DOUBLE, "Comp4" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_LOADINGS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_LOADINGS_INFO', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_SCORES', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'PCA', 'DEVUSER', 'P_PCA', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "ID", "LIFESPEND", "NEWSPEND", "INCOME", "LOYALTY"
		FROM "PAL"."CUSTOMERS"
	;
CREATE COLUMN TABLE "LOADINGS" LIKE "T_LOADINGS";
CREATE COLUMN TABLE "LOADINGS_INFO" LIKE "T_LOADINGS_INFO";
CREATE COLUMN TABLE "SCORES" LIKE "T_SCORES";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO "#PARAMS" VALUES ('SCALING', 1, null, null); -- 0: No; 1:Yes
INSERT INTO "#PARAMS" VALUES ('SCORES', 1, null, null); -- 0: No; 1:Yes

TRUNCATE TABLE "LOADINGS";
TRUNCATE TABLE "LOADINGS_INFO";
TRUNCATE TABLE "SCORES";

CALL "P_PCA" ("V_DATA", "#PARAMS", "LOADINGS", "LOADINGS_INFO", "SCORES") WITH OVERVIEW;

SELECT * FROM "LOADINGS";
SELECT * FROM "LOADINGS_INFO";
SELECT * FROM "SCORES";
