-- CHECK AFL PAL FUNCTIONS ARE INSTALLED
SELECT * FROM SYS.AFL_FUNCTIONS WHERE PACKAGE_NAME='PAL';

-- START SCRIPT SERVER
ALTER SYSTEM ALTER CONFIGURATION ('daemon.ini', 'SYSTEM') SET ('scriptserver', 'instances') = '1' WITH RECONFIGURE;

-- CREATE USER FOR AFL DEVELOPMENT
CREATE USER AFLUSER PASSWORD Password1;
GRANT CREATE ANY, ALTER, DROP, EXECUTE, SELECT, INSERT, UPDATE, DELETE, INDEX, DEBUG, TRIGGER, REFERENCES ON SCHEMA PAL TO AFLUSER;
GRANT EXECUTE ON SYSTEM.AFL_WRAPPER_GENERATOR TO AFLUSER;
GRANT EXECUTE ON SYSTEM.AFL_WRAPPER_ERASER TO AFLUSER;
GRANT AFL__SYS_AFL_AFLPAL_EXECUTE TO AFLUSER;
