-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_STATS";
DROP TYPE "T_COEFFICIENT";
DROP TYPE "T_COVARIANCE";
DROP TYPE "T_HAZARD";
DROP TYPE "T_FITTED";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_COXPH_E');
DROP TABLE "DATA";
DROP TABLE "STATS";
DROP TABLE "COEFFICIENT";
DROP TABLE "COVARIANCE";
DROP TABLE "FITTED";
DROP TABLE "HAZARD";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "TIME" DOUBLE, "STATUS" INTEGER, "X1" DOUBLE, "X2" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_STATS" AS TABLE ("NAME" VARCHAR(500), "VALUE" VARCHAR(5000));
CREATE TYPE "T_COEFFICIENT" AS TABLE ("NAME" VARCHAR(500), "MEANS" DOUBLE, "BETA" DOUBLE, "STDERR" DOUBLE, "SCORE" DOUBLE, "PROBABILITY" DOUBLE, "CI_LOWER" DOUBLE, "CI_UPPER" DOUBLE);
CREATE TYPE "T_COVARIANCE" AS TABLE ("ROW" VARCHAR(500), "COL" VARCHAR(500), "COV" DOUBLE);
CREATE TYPE "T_HAZARD" AS TABLE ("TIME" DOUBLE, "HAZARD" DOUBLE, "SURVIVAL" DOUBLE);
CREATE TYPE "T_FITTED" AS TABLE ("ID" INTEGER, "LP" DOUBLE, "RESPONSE" DOUBLE);
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_STATS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_COEFFICIENT', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_COVARIANCE', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_HAZARD', 'OUT');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_FITTED', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'COXPHESTIMATE', 'DEVUSER', 'P_COXPH_E', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 4, 1, 0, 0);
INSERT INTO "DATA" VALUES (2, 3, 1, 2, 0);
INSERT INTO "DATA" VALUES (3, 1, 1, 1, 0);
INSERT INTO "DATA" VALUES (4, 1, 0, 1, 0);
INSERT INTO "DATA" VALUES (5, 2, 1, 1, 1);
INSERT INTO "DATA" VALUES (6, 2, 1, 0, 1);
INSERT INTO "DATA" VALUES (7, 3, 0, 0, 1);
CREATE COLUMN TABLE "STATS" LIKE "T_STATS";
CREATE COLUMN TABLE "COEFFICIENT" LIKE "T_COEFFICIENT";
CREATE COLUMN TABLE "COVARIANCE" LIKE "T_COVARIANCE";
CREATE COLUMN TABLE "HAZARD" LIKE "T_HAZARD";
CREATE COLUMN TABLE "FITTED" LIKE "T_FITTED";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('TIE_METHOD', null, null, 'efron');
INSERT INTO "#PARAMS" VALUES ('CALCULATE_HAZARD', 1, null, null);
INSERT INTO "#PARAMS" VALUES ('OUTPUT_FITTED', 1, null, null);

TRUNCATE TABLE "STATS";
TRUNCATE TABLE "COEFFICIENT";
TRUNCATE TABLE "COVARIANCE";
TRUNCATE TABLE "HAZARD";
TRUNCATE TABLE "FITTED";

CALL "P_COXPH_E" ("DATA", "#PARAMS", "STATS", "COEFFICIENT", "COVARIANCE", "HAZARD", "FITTED") WITH OVERVIEW;

SELECT * FROM "DATA";
SELECT * FROM "STATS";
SELECT * FROM "COEFFICIENT";
SELECT * FROM "COVARIANCE";
SELECT * FROM "HAZARD";
SELECT * FROM "FITTED";
