SELECT *,
	SERIES_FILTER(VALUE => "SALES_AMOUNT", METHOD_NAME => 'SINGLESMOOTH', ALPHA => 0.2) 
		OVER (ORDER BY "CALENDAR_ID") AS "SALES_AMOUNT_SES",
	SERIES_FILTER(VALUE => "SALES_AMOUNT", METHOD_NAME => 'DOUBLESMOOTH', ALPHA => 0.2, BETA => 0.3) 
		OVER (ORDER BY "CALENDAR_ID") AS "SALES_AMOUNT_DES"
 FROM (
		SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		 FROM "PAL"."ORDER_FACTS"
		 WHERE "ITEM_ID" BETWEEN 0 AND 9
		 GROUP BY "CALENDAR_ID"
		 UNION ALL SELECT 24, null FROM DUMMY
		 )
 ;
