-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_MODEL";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_SR');
DROP TABLE "RESULTS";
DROP TABLE "MODEL";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "INCOME" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "INCOME" DOUBLE);
CREATE TYPE "T_MODEL" AS TABLE ("ID" INTEGER, "MODEL" VARCHAR(5000));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_MODEL', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'SCALINGRANGE', 'DEVUSER', 'P_SR', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "MODEL" LIKE "T_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('SCALING_METHOD', 0, null, null);
INSERT INTO "#PARAMS" VALUES ('NEW_MAX', null, 1.0, null);
INSERT INTO "#PARAMS" VALUES ('NEW_MIN', null, 0.0, null);
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "MODEL";

CALL "P_SR" ("PAL"."CUSTOMERS_INCOME", "#PARAMS", "RESULTS", "MODEL") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "MODEL";
