SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_DP_DATA;
DROP TYPE PAL_T_DP_PARAMS;
DROP TYPE PAL_T_DP_RESULTS;
DROP TABLE PAL_DP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_DP');
DROP TABLE DP_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_DP_DATA AS TABLE (ID INTEGER, POLICY NVARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION NVARCHAR(10), FRAUD NVARCHAR(10));
CREATE TYPE PAL_T_DP_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_DP_RESULTS AS TABLE (ID INTEGER, PARTITION INTEGER);

CREATE COLUMN TABLE PAL_DP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_DP_SIGNATURE VALUES (1, 'PAL.PAL_T_DP_DATA', 'in');
INSERT INTO PAL_DP_SIGNATURE VALUES (2, 'PAL.PAL_T_DP_PARAMS', 'in');
INSERT INTO PAL_DP_SIGNATURE VALUES (3, 'PAL.PAL_T_DP_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_DP', 'AFLPAL', 'PARTITION', PAL_DP_SIGNATURE);

-- app setup
CREATE COLUMN TABLE DP_RESULTS LIKE PAL_T_DP_RESULTS;

-- app runtime
DROP TABLE #DP_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #DP_PARAMS LIKE PAL_T_DP_PARAMS;
INSERT INTO #DP_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO #DP_PARAMS VALUES ('PARTITION_METHOD', 1, null, null); -- 0:Random, 1:Stratified
--INSERT INTO #DP_PARAMS VALUES ('STRATIFIED_COLUMN', null, null, 'OCCUPATION');
--INSERT INTO #DP_PARAMS VALUES ('TRAINING_PERCENT', null, 0.5, null);
--INSERT INTO #DP_PARAMS VALUES ('TESTING_PERCENT', null, 0.3, null);
--INSERT INTO #DP_PARAMS VALUES ('VALIDATION_PERCENT', null, 0.2, null);
--INSERT INTO #DP_PARAMS VALUES ('RANDOM_SEED', 17, null, null);

TRUNCATE TABLE DP_RESULTS;

CALL _SYS_AFL.PAL_DP (CLAIMS, #DP_PARAMS, DP_RESULTS) WITH OVERVIEW;

SELECT * FROM DP_RESULTS ORDER BY ID;
SELECT * FROM CLAIMS WHERE ID IN (SELECT ID FROM DP_RESULTS WHERE PARTITION=1) ORDER BY ID;
