SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_SVP_DATA;
DROP TYPE PAL_T_SVP_PREDICT;
DROP TABLE PAL_SVP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_SVP');
DROP TABLE SVP_DATA;
DROP TABLE SVP_PREDICT;

-- PAL setup
CREATE TYPE PAL_T_SVP_DATA AS TABLE (ID INTEGER, POLICY INTEGER, AGE INTEGER, AMOUNT INTEGER, OCCUPATION INTEGER);
CREATE TYPE PAL_T_SVP_PREDICT AS TABLE (ID INTEGER, FRAUD INTEGER);

CREATE COLUMN TABLE PAL_SVP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SVP_SIGNATURE VALUES (1, 'PAL.PAL_T_SVP_DATA', 'in');
INSERT INTO PAL_SVP_SIGNATURE VALUES (2, 'PAL.PAL_T_SV_PARAMS', 'in');
INSERT INTO PAL_SVP_SIGNATURE VALUES (3, 'PAL.PAL_T_SV_MODEL1', 'in');
INSERT INTO PAL_SVP_SIGNATURE VALUES (4, 'PAL.PAL_T_SV_MODEL2', 'in');
INSERT INTO PAL_SVP_SIGNATURE VALUES (5, 'PAL.PAL_T_SVP_PREDICT', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SVP', 'AFLPAL', 'SVMPREDICT', PAL_SVP_SIGNATURE);

-- app setup
CREATE COLUMN TABLE SVP_DATA LIKE PAL_T_SVP_DATA;
CREATE COLUMN TABLE SVP_PREDICT LIKE PAL_T_SVP_PREDICT;

-- app runtime
TRUNCATE TABLE SVP_DATA;
INSERT INTO SVP_DATA VALUES (1, 2, 41, 900, 2);
INSERT INTO SVP_DATA VALUES (2, 3, 26, 6000, 3);
INSERT INTO SVP_DATA VALUES (3, 1, 54, 2500, 2);
INSERT INTO SVP_DATA VALUES (4, 2, 33, 1200, 3);
INSERT INTO SVP_DATA VALUES (5, 1, 38, 2800, 1);

DROP TABLE #SVP_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #SVP_PARAMS LIKE PAL_T_SV_PARAMS;
INSERT INTO #SVP_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);

TRUNCATE TABLE SVP_PREDICT;

CALL _SYS_AFL.PAL_SVP (SVP_DATA, #SVP_PARAMS, SV_MODEL1, SV_MODEL2, SVP_PREDICT) WITH OVERVIEW;

SELECT * FROM SVP_PREDICT;


