-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RULES";
DROP TYPE "T_ANTECEDENT";
DROP TYPE "T_CONSEQUENT";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_KORD');
DROP VIEW "V_DATA";
DROP TABLE "RULES";
DROP TABLE "ANTECEDENT";
DROP TABLE "CONSEQUENT";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ORDERID" INTEGER, "PRODUCTID" INTEGER);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RULES" AS TABLE ("RULEID" INT, "SUPPORT" DOUBLE, "CONFIDENCE" DOUBLE, "LIFT" DOUBLE, "LEVERAGE" DOUBLE, "MEASURE_VALUE" DOUBLE);
CREATE TYPE "T_ANTECEDENT" AS TABLE ("RULEID" INT, "PRODUCTID" VARCHAR(500));
CREATE TYPE "T_CONSEQUENT" AS TABLE ("RULEID" INT, "PRODUCTID" VARCHAR(500));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RULES', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_ANTECEDENT', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_CONSEQUENT', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'KORD', 'DEVUSER', 'P_KORD', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "ORDERID", "PRODUCTID" 
		FROM "PAL"."FCTCUSTOMERORDER"
	;
CREATE COLUMN TABLE "RULES" LIKE "T_RULES";
CREATE COLUMN TABLE "ANTECEDENT" LIKE "T_ANTECEDENT";
CREATE COLUMN TABLE "CONSEQUENT" LIKE "T_CONSEQUENT";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO "#PARAMS" VALUES ('TOPK', 200, null, null);
INSERT INTO "#PARAMS" VALUES ('MEASURE_TYPE', 0, null, null); -- 0 : leverage ; 1 : lift
--INSERT INTO "#PARAMS" VALUES ('MAX_ANTECEDENT', 4, null, null);
--INSERT INTO "#PARAMS" VALUES ('MIN_SUPPORT', null, 0, null);
--INSERT INTO "#PARAMS" VALUES ('MIN_CONFIDENCE', null, 0, null);
--INSERT INTO "#PARAMS" VALUES ('MIN_COVERAGE', null, 0, null); -- default is MIN_SUPPORT value
--INSERT INTO "#PARAMS" VALUES ('MIN_MEASURE', null, 0, null); -- min for leverage/lift
--INSERT INTO "#PARAMS" VALUES ('IS_USE_EPSILON', 0, null, null); -- 0 : no ; 1 : yes
--INSERT INTO "#PARAMS" VALUES ('EPSILON', null, 0, null); -- use when IS_USE_EPSILON <> 0

TRUNCATE TABLE "RULES";
TRUNCATE TABLE "ANTECEDENT";
TRUNCATE TABLE "CONSEQUENT";

CALL "P_KORD" ("V_DATA", "#PARAMS", "RULES", "ANTECEDENT", "CONSEQUENT") WITH OVERVIEW;

SELECT * FROM "RULES";
SELECT * FROM "ANTECEDENT";
SELECT * FROM "CONSEQUENT";
