-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_WNT');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("CALENDAR_ID" INTEGER, "SALES_AMOUNT" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("NAME" VARCHAR(60), "WHITENOISE" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'WHITENOISETEST', 'DEVUSER', 'P_WNT', "SIGNATURE");

-- data setup
CREATE VIEW "V_DATA" AS 
	SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		FROM "PAL"."ORDER_FACTS"
		WHERE "ITEM_ID" BETWEEN 0 AND 9
		GROUP BY "CALENDAR_ID" 
		ORDER BY "CALENDAR_ID"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('LAG', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('PROBABILITY', null, 0.9, null);

TRUNCATE TABLE "RESULTS";

CALL "P_WNT" ("V_DATA", "#PARAMS", "RESULTS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
