SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_SU_DATA;
DROP TYPE PAL_T_SU_PARAMS;
DROP TYPE PAL_T_SU_RESULTS;
DROP TABLE PAL_SU_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_SU');
DROP VIEW V_SU_DATA;
DROP TABLE SU_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_SU_DATA AS TABLE (LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_SU_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SU_RESULTS AS TABLE (NAME VARCHAR(100), LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);

CREATE COLUMN TABLE PAL_SU_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SU_SIGNATURE VALUES (1, 'PAL.PAL_T_SU_DATA', 'in');
INSERT INTO PAL_SU_SIGNATURE VALUES (2, 'PAL.PAL_T_SU_PARAMS', 'in');
INSERT INTO PAL_SU_SIGNATURE VALUES (3, 'PAL.PAL_T_SU_RESULTS', 'out');

GRANT SELECT ON PAL_SU_SIGNATURE to SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SU', 'AFLPAL', 'UNIVARSTAT', PAL_SU_SIGNATURE);

-- app setup
CREATE VIEW V_SU_DATA AS 
	SELECT LIFESPEND, NEWSPEND, INCOME, LOYALTY 
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE SU_RESULTS LIKE PAL_T_SU_RESULTS;

-- app runtime
DROP TABLE #SU_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #SU_PARAMS LIKE PAL_T_SU_PARAMS;
INSERT INTO #SU_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO #SU_PARAMS VALUES ('SKEWNESS_TYPE', 1, null, null); -- 0: Definition 1, 1: Definition 2, 2: Definition 3			
--INSERT INTO #SU_PARAMS VALUES ('KURTOSIS_TYPE', 1, null, null); -- 0: Definition 1, 1: Definition 2, 2: Definition 3			
--INSERT INTO #SU_PARAMS VALUES ('DATASET_TYPE', 0, null, null); -- 0: sample, 1: population

TRUNCATE TABLE SU_RESULTS;

CALL _SYS_AFL.PAL_SU (V_SU_DATA, #SU_PARAMS, SU_RESULTS) WITH OVERVIEW;

SELECT * FROM V_SU_DATA;
SELECT * FROM SU_RESULTS;
