SET SCHEMA PAL; 

-- cleanup
DROP TYPE PAL_T_RG_DATA;
DROP TYPE PAL_T_RG_PARAMS;
DROP TYPE PAL_T_RG_MODEL;
DROP TYPE PAL_T_RG_PMML;
DROP TABLE PAL_RG_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_RG');
DROP VIEW V_RG_DATA;
DROP TABLE RG_MODEL;
DROP TABLE RG_PMML;

-- PAL setup
CREATE TYPE PAL_T_RG_DATA AS TABLE (LIFESPEND DOUBLE, NEWSPEND DOUBLE, JOB VARCHAR(60));
CREATE TYPE PAL_T_RG_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_RG_MODEL AS TABLE (P INTEGER, K VARCHAR(100), W DOUBLE);
CREATE TYPE PAL_T_RG_PMML AS TABLE (ID INTEGER, PMML VARCHAR(5000));

CREATE COLUMN TABLE PAL_RG_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_RG_SIGNATURE VALUES (1, 'PAL.PAL_T_RG_DATA', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (2, 'PAL.PAL_T_RG_PARAMS', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (3, 'PAL.PAL_T_RG_MODEL', 'out');
INSERT INTO PAL_RG_SIGNATURE VALUES (6, 'PAL.PAL_T_RG_PMML', 'out');

GRANT SELECT ON PAL_RG_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_RG', 'AFLPAL', 'LRMCTR', PAL_RG_SIGNATURE);

-- app setup
CREATE VIEW V_RG_DATA AS 
	SELECT  CAST(l.LIFESPEND AS DOUBLE) AS LIFESPEND,
			CAST(n.NEWSPEND AS DOUBLE) AS NEWSPEND,
			CAST(c.CUSTOMER_JOB AS VARCHAR(60)) AS JOB
	 FROM CUSTOMER c
	 INNER JOIN (
			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS LIFESPEND
			 FROM ORDER_FACTS
			 GROUP BY CUSTOMER_ID
				) l ON(c.CUSTOMER_ID = l.CUSTOMER_ID)
	 INNER JOIN (
 			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS NEWSPEND
			 FROM ORDER_FACTS
			 WHERE CALENDAR_ID=23
			 GROUP BY CUSTOMER_ID
				) n ON(c.CUSTOMER_ID = n.CUSTOMER_ID)
	 ;
CREATE COLUMN TABLE RG_MODEL LIKE PAL_T_RG_MODEL;
CREATE COLUMN TABLE RG_PMML LIKE PAL_T_RG_PMML;

-- app runtime
DROP TABLE #RG_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #RG_PARAMS LIKE PAL_T_RG_PARAMS;
INSERT INTO #RG_PARAMS VALUES ('THREAD_NUMBER', 4, null, null);
INSERT INTO #RG_PARAMS VALUES ('MAX_ITERATION', 500, null, null);
INSERT INTO #RG_PARAMS VALUES ('PMML_EXPORT', 2, null, null);

TRUNCATE TABLE RG_MODEL;
TRUNCATE TABLE RG_PMML;

CALL _SYS_AFL.PAL_RG (V_RG_DATA, #RG_PARAMS, RG_MODEL, RG_PMML) WITH OVERVIEW;

SELECT * FROM RG_MODEL;
SELECT * FROM RG_PMML;
