-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_CV";
DROP TYPE "T_MODEL";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_GB_M');
DROP VIEW "V_DATA";
DROP TABLE "CV";
DROP TABLE "MODEL";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("POLICY" NVARCHAR(10), "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" NVARCHAR(10), "FRAUD" NVARCHAR(10));
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_CV" AS TABLE ("NAME" VARCHAR(500), "VALUE" VARCHAR(5000));
CREATE TYPE "T_MODEL" AS TABLE ("ID" INTEGER, "NAME" VARCHAR(500), "VALUES" VARCHAR(5000));
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_CV', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_MODEL', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'GBDTTRAIN', 'DEVUSER', 'P_GB_M', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS SELECT "POLICY", "AGE", "AMOUNT", "OCCUPATION", "FRAUD" FROM "PAL"."CLAIMS";
CREATE COLUMN TABLE "CV" LIKE "T_CV";
CREATE COLUMN TABLE "MODEL" LIKE "T_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('ITER_NUM', 5, null, null);
INSERT INTO "#PARAMS" VALUES ('FOLD_NUM', 5, null, null);
INSERT INTO "#PARAMS" VALUES ('MAX_TREE_DEPTH', 6, null, null);
INSERT INTO "#PARAMS" VALUES ('MIN_SPLIT_LOSS', null, 0.0, null);
INSERT INTO "#PARAMS" VALUES ('LEARNING_RATE', null, 0.5, null);
INSERT INTO "#PARAMS" VALUES ('CV_METRIC', null, null, 'ERROR_RATE');
INSERT INTO "#PARAMS" VALUES ('REF_METRIC', null, null, 'AUC');
INSERT INTO "#PARAMS" VALUES ('CONTINUOUS_COL', null, null, 'AGE');
INSERT INTO "#PARAMS" VALUES ('CONTINUOUS_COL', null, null, 'AMOUNT');

TRUNCATE TABLE "CV";
TRUNCATE TABLE "MODEL";

CALL "P_GB_M" ("V_DATA", "#PARAMS", "CV", "MODEL") WITH OVERVIEW;

SELECT * FROM "CV";
SELECT * FROM "MODEL";
