-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_COXPH_P');
DROP TABLE "DATA";
DROP TABLE "RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "X1" DOUBLE, "X2" DOUBLE);
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "PREDICTED" DOUBLE, "STDERR" DOUBLE, "CI_LOWER" DOUBLE, "CI_UPPER" DOUBLE);
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_COEFFICIENT', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_COVARIANCE', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_RESULTS', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'COXPHPREDICT', 'DEVUSER', 'P_COXPH_P', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 0, 0);
INSERT INTO "DATA" VALUES (2, 2, 0);
INSERT INTO "DATA" VALUES (3, 1, 0);
INSERT INTO "DATA" VALUES (4, 1, 0);
INSERT INTO "DATA" VALUES (5, 1, 1);
INSERT INTO "DATA" VALUES (6, 0, 1);
INSERT INTO "DATA" VALUES (7, 0, 1);
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('SIGNIFICANCE_LEVEL', null, 0.05, null); -- default: 0.05
INSERT INTO "#PARAMS" VALUES ('TYPE', null, null, 'risk'); -- risk; lp (default:risk)

TRUNCATE TABLE "RESULTS";

CALL "P_COXPH_P" ("DATA", "COEFFICIENT", "COVARIANCE", "#PARAMS", "RESULTS") WITH OVERVIEW;

SELECT * FROM "DATA";
SELECT * FROM "RESULTS";
