SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_NBP_DATA;
DROP TYPE PAL_T_NBP_PREDICT;
DROP TABLE PAL_NBP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_NBP');
DROP TABLE NBP_DATA;
DROP TABLE NBP_PREDICT;

-- PAL setup
CREATE TYPE PAL_T_NBP_DATA AS TABLE (ID INTEGER, POLICY VARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION VARCHAR(10));
CREATE TYPE PAL_T_NBP_PREDICT AS TABLE (ID INTEGER, FRAUD VARCHAR(10));

CREATE COLUMN TABLE PAL_NBP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_NBP_SIGNATURE VALUES (1, 'PAL.PAL_T_NBP_DATA', 'in');
INSERT INTO PAL_NBP_SIGNATURE VALUES (2, 'PAL.PAL_T_NB_PARAMS', 'in');
INSERT INTO PAL_NBP_SIGNATURE VALUES (3, 'PAL.PAL_T_NB_MODEL', 'in');
INSERT INTO PAL_NBP_SIGNATURE VALUES (4, 'PAL.PAL_T_NBP_PREDICT', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_NBP', 'AFLPAL', 'NBCPREDICT', PAL_NBP_SIGNATURE);

-- app setup
CREATE COLUMN TABLE NBP_DATA LIKE PAL_T_NBP_DATA;
CREATE COLUMN TABLE NBP_PREDICT LIKE PAL_T_NBP_PREDICT;

-- app runtime
TRUNCATE TABLE NBP_DATA;
INSERT INTO NBP_DATA VALUES (1, 'Travel', 41, 900, 'IT');
INSERT INTO NBP_DATA VALUES (2, 'Vehicle', 26, 6000, 'Marketing');
INSERT INTO NBP_DATA VALUES (3, 'Home', 54, 2500, 'Marketing');
INSERT INTO NBP_DATA VALUES (4, 'Vehicle', 33, 1200, 'Marketing');
INSERT INTO NBP_DATA VALUES (5, 'Home', 38, 2500, 'Sales');

DROP TABLE #NBP_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #NBP_PARAMS LIKE PAL_T_NB_PARAMS;
INSERT INTO #NBP_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);

TRUNCATE TABLE NBP_PREDICT;

CALL _SYS_AFL.PAL_NBP (NBP_DATA, #NBP_PARAMS, NB_MODEL, NBP_PREDICT) WITH OVERVIEW;

SELECT d.*, p.FRAUD 
 FROM NBP_DATA d
 INNER JOIN NBP_PREDICT p ON (p.ID=d.ID)
 ;

