SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_B_DATA;
DROP TYPE PAL_T_B_PARAMS;
DROP TYPE PAL_T_B_RESULTS;
DROP TABLE PAL_B_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_B');
DROP TABLE B_RESULTS;
DROP VIEW V_B_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_B_DATA AS TABLE (ID INTEGER, VALUE DOUBLE);
CREATE TYPE PAL_T_B_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_B_RESULTS AS TABLE (ID INTEGER, VALUE_GROUP INTEGER, PRE_RESULT INTEGER);

CREATE COLUMN TABLE PAL_B_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_B_SIGNATURE VALUES (1, 'PAL.PAL_T_B_DATA', 'in');
INSERT INTO PAL_B_SIGNATURE VALUES (2, 'PAL.PAL_T_B_PARAMS', 'in');
INSERT INTO PAL_B_SIGNATURE VALUES (3, 'PAL.PAL_T_B_RESULTS', 'out');

GRANT SELECT ON PAL_B_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_B', 'AFLPAL', 'BINNING', PAL_B_SIGNATURE);

-- app setup
CREATE COLUMN TABLE B_RESULTS LIKE PAL_T_B_RESULTS;

CREATE VIEW V_B_RESULTS AS
	SELECT r.ID, VALUE, VALUE_GROUP, (1/200)*100 AS FREQ_PCT
	 FROM RD_RESULTS r
	 INNER JOIN B_RESULTS b ON (b.ID=r.ID)
	 ;

-- app runtime
DROP TABLE #B_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #B_PARAMS LIKE PAL_T_B_PARAMS;
INSERT INTO #B_PARAMS VALUES ('BINNING_METHOD', 0, null, null);
INSERT INTO #B_PARAMS VALUES ('SMOOTH_METHOD', 0, null, null);
INSERT INTO #B_PARAMS VALUES ('BIN_NUMBER', 100, null, null);

TRUNCATE TABLE B_RESULTS;

CALL _SYS_AFL.PAL_B (RD_RESULTS, #B_PARAMS, B_RESULTS) WITH OVERVIEW;

