-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_SES');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP VIEW "V_RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("CALENDAR_ID" INT, "SALES_AMOUNT" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("CALENDAR_ID" INT, "SALES_AMOUNT" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'SINGLESMOOTH', 'DEVUSER', 'P_SES', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		FROM "PAL"."ORDER_FACTS"
		WHERE "ITEM_ID" BETWEEN 0 AND 9
		GROUP BY "CALENDAR_ID" 
		ORDER BY "CALENDAR_ID"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE VIEW "V_RESULTS" AS
	SELECT 
		CASE WHEN a."CALENDAR_ID" IS NOT NULL THEN a."CALENDAR_ID" ELSE b."CALENDAR_ID" END AS "CALENDAR_ID", 
		a."SALES_AMOUNT", 
		ROUND(b."SALES_AMOUNT") AS "SALES_AMOUNT_PREDICTED"
	 FROM "V_DATA" a 
	 FULL JOIN "RESULTS" b ON (a."CALENDAR_ID"=b."CALENDAR_ID") 
	 ;

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('RAW_DATA_COL', 1, null, null);
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.3, null);
INSERT INTO "#PARAMS" VALUES ('STARTTIME', 1, null, null);
--INSERT INTO "#PARAMS" VALUES ('EXPOST_FLAG', 1, null, null); -- 0 : do not output; 1 : output expost forecast

TRUNCATE TABLE "RESULTS";

CALL "P_SES" ("V_DATA", "#PARAMS", "RESULTS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "V_RESULTS";
