SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_SC_DATA;
DROP TYPE PAL_T_SC_PARAMS;
DROP TYPE PAL_T_SC_RESULTS;
DROP TYPE PAL_T_SC_RESULTS_INFO;
DROP TABLE PAL_SC_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_SC');
DROP VIEW V_SC_DATA;
DROP TABLE SC_RESULTS;
DROP TABLE SC_RESULTS_INFO;

-- PAL setup
CREATE TYPE PAL_T_SC_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, INCOME DOUBLE);
CREATE TYPE PAL_T_SC_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SC_RESULTS AS TABLE (ID INTEGER, LIFESPEND DOUBLE, INCOME DOUBLE);
CREATE TYPE PAL_T_SC_RESULTS_INFO AS TABLE (NAME VARCHAR(100), VALUE DOUBLE);

CREATE COLUMN TABLE PAL_SC_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SC_SIGNATURE VALUES (1, 'PAL.PAL_T_SC_DATA', 'in');
INSERT INTO PAL_SC_SIGNATURE VALUES (2, 'PAL.PAL_T_SC_PARAMS', 'in');
INSERT INTO PAL_SC_SIGNATURE VALUES (3, 'PAL.PAL_T_SC_RESULTS', 'out');
INSERT INTO PAL_SC_SIGNATURE VALUES (4, 'PAL.PAL_T_SC_RESULTS_INFO', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SC', 'AFLPAL', 'CHISQTESTIND', PAL_SC_SIGNATURE);

-- app setup
CREATE VIEW V_SC_DATA AS
	SELECT ID, LIFESPEND, INCOME
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE SC_RESULTS LIKE PAL_T_SC_RESULTS;
CREATE COLUMN TABLE SC_RESULTS_INFO LIKE PAL_T_SC_RESULTS_INFO;

-- app runtime
DROP TABLE #SC_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #SC_PARAMS LIKE PAL_T_SC_PARAMS;
INSERT INTO #SC_PARAMS VALUES ('CORRECTION_TYPE', 0, null, null); -- 0:No Yates, 1: Perform Yates Correction
TRUNCATE TABLE SC_RESULTS;
TRUNCATE TABLE SC_RESULTS_INFO;

CALL _SYS_AFL.PAL_SC (V_SC_DATA, #SC_PARAMS, SC_RESULTS, SC_RESULTS_INFO) WITH OVERVIEW;

SELECT * FROM V_SC_DATA;
SELECT * FROM SC_RESULTS;
SELECT * FROM SC_RESULTS_INFO;
