SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_SR_DATA AS TABLE (ID INTEGER, INCOME INTEGER);
CREATE TYPE PAL_T_SR_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SR_RESULTS AS TABLE (ID INTEGER, INCOME DOUBLE);

CREATE COLUMN TABLE PAL_SR_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SR_SIGNATURE VALUES (1, 'PAL.PAL_T_SR_DATA', 'in');
INSERT INTO PAL_SR_SIGNATURE VALUES (2, 'PAL.PAL_T_SR_PARAMS', 'in');
INSERT INTO PAL_SR_SIGNATURE VALUES (3, 'PAL.PAL_T_SR_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SR', 'AFLPAL', 'SCALINGRANGE', PAL_SR_SIGNATURE);

-- app setup

CREATE COLUMN TABLE SR_PARAMS LIKE PAL_T_SR_PARAMS;
CREATE COLUMN TABLE SR_RESULTS LIKE PAL_T_SR_RESULTS;

INSERT INTO SR_PARAMS VALUES ('SCALING_METHOD', 0, null, null);
INSERT INTO SR_PARAMS VALUES ('NEW_MAX', null, 1.0, null);
INSERT INTO SR_PARAMS VALUES ('NEW_MIN', null, 0.0, null);
INSERT INTO SR_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);

-- app runtime

UPDATE SR_PARAMS SET INTARGS=1 WHERE NAME='SCALING_METHOD';

TRUNCATE TABLE SR_RESULTS;

CALL _SYS_AFL.PAL_SR (CUSTOMERS_INCOME, SR_PARAMS, SR_RESULTS) WITH OVERVIEW;


