SET SCHEMA PAL; 

-- PAL setup

CREATE TYPE PAL_T_RG_DATA AS TABLE (LIFESPEND INTEGER, NEWSPEND INTEGER, GENDER INTEGER);
CREATE TYPE PAL_T_RG_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_RG_COEFF AS TABLE (ID INTEGER, AI DOUBLE);
CREATE TYPE PAL_T_RG_PMML AS TABLE (ID INTEGER, PMML VARCHAR(5000));

CREATE COLUMN TABLE PAL_RG_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_RG_SIGNATURE VALUES (1, 'PAL.PAL_T_RG_DATA', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (2, 'PAL.PAL_T_RG_PARAMS', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (3, 'PAL.PAL_T_RG_COEFF', 'out');
INSERT INTO PAL_RG_SIGNATURE VALUES (6, 'PAL.PAL_T_RG_PMML', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_RG', 'AFLPAL', 'LOGISTICREGRESSION', PAL_RG_SIGNATURE);

-- app setup
CREATE VIEW V_RG_DATA AS 
	SELECT TOP 1000 l.LIFESPEND, n.NEWSPEND, c.CUSTOMER_GENDER_ID AS GENDER
	 FROM CUSTOMER c
	 INNER JOIN (
			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS LIFESPEND
			 FROM ORDER_FACTS
			 GROUP BY CUSTOMER_ID
				) l ON(c.CUSTOMER_ID = l.CUSTOMER_ID)
	 INNER JOIN (
 			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS NEWSPEND
			 FROM ORDER_FACTS
			 WHERE CALENDAR_ID=23
			 GROUP BY CUSTOMER_ID
				) n ON(c.CUSTOMER_ID = n.CUSTOMER_ID)
	 ;
CREATE COLUMN TABLE RG_PARAMS LIKE PAL_T_RG_PARAMS;
CREATE COLUMN TABLE RG_COEFF LIKE PAL_T_RG_COEFF;
CREATE COLUMN TABLE RG_PMML LIKE PAL_T_RG_PMML;

INSERT INTO RG_PARAMS VALUES ('THREAD_NUMBER', 4, null, null);
INSERT INTO RG_PARAMS VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO RG_PARAMS VALUES ('EXIT_THRESHOLD', null, 0.00001, null);
INSERT INTO RG_PARAMS VALUES ('VARIABLE_NUM', 2, null, null);
INSERT INTO RG_PARAMS VALUES ('METHOD', 0, null, null);
INSERT INTO RG_PARAMS VALUES ('PMML_EXPORT', 2, null, null);

-- app runtime

--UPDATE RG_PARAMS SET INTARGS=1000 WHERE NAME='MAX_ITERATION';

TRUNCATE TABLE RG_COEFF;
TRUNCATE TABLE RG_PMML;

CALL _SYS_AFL.PAL_RG (V_RG_DATA, RG_PARAMS, RG_COEFF, RG_PMML) WITH OVERVIEW;


