-- cleanup
DROP TYPE "T_CLUSTERED";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_CA');
DROP TABLE "DATA";
DROP TABLE "CLUSTERED";

-- procedure setup
CREATE TYPE "T_CLUSTERED" AS TABLE ("ID" INTEGER, "CLUSTER_NUMBER" INTEGER, "DISTANCE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_MODEL', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_CLUSTERED', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'CLUSTERASSIGNMENT', 'DEVUSER', 'P_CA', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 7.1, 3.7, 6.2, 2.6);
INSERT INTO "DATA" VALUES (2, 5.5, 3.5, 1.4, 0.5);

CREATE COLUMN TABLE "CLUSTERED" LIKE "T_CLUSTERED";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";

TRUNCATE TABLE "CLUSTERED";

CALL "P_CA" ("DATA", "MODEL", "#PARAMS", "CLUSTERED") WITH OVERVIEW;

SELECT * FROM "CLUSTERED";
