SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_FP_DATA;
DROP TYPE PAL_T_FP_PARAMS;
DROP TYPE PAL_T_FP_RULES;
DROP TABLE PAL_FP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_FP');
DROP VIEW V_FP_DATA;
DROP TABLE FP_RULES;

-- PAL setup
CREATE TYPE PAL_T_FP_DATA AS TABLE (ORDERID INTEGER, PRODUCTID INTEGER);
CREATE TYPE PAL_T_FP_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_FP_RULES AS TABLE (PRERULE VARCHAR(500), POSTRULE VARCHAR(500), SUPPORT DOUBLE, CONFIDENCE DOUBLE, LIFT DOUBLE);

CREATE COLUMN TABLE PAL_FP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_FP_SIGNATURE VALUES (1, 'PAL.PAL_T_FP_DATA', 'in');
INSERT INTO PAL_FP_SIGNATURE VALUES (2, 'PAL.PAL_T_FP_PARAMS', 'in');
INSERT INTO PAL_FP_SIGNATURE VALUES (3, 'PAL.PAL_T_FP_RULES', 'out');

GRANT SELECT ON PAL_FP_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_FP', 'AFLPAL', 'FPGROWTH', PAL_FP_SIGNATURE);

-- app setup
CREATE VIEW V_FP_DATA AS 
	SELECT ORDERID, PRODUCTID 
		FROM FCTCUSTOMERORDER 
	;
CREATE COLUMN TABLE FP_RULES LIKE PAL_T_FP_RULES;

-- app runtime
DROP TABLE #FP_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #FP_PARAMS LIKE PAL_T_FP_PARAMS;
INSERT INTO #FP_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #FP_PARAMS VALUES ('MIN_SUPPORT', null, 0.005, null);
INSERT INTO #FP_PARAMS VALUES ('MIN_CONFIDENCE', null, 0.001, null);
INSERT INTO #FP_PARAMS VALUES ('MAXLENGTH', 5, null, null);

TRUNCATE TABLE FP_RULES;

CALL _SYS_AFL.PAL_FP (V_FP_DATA, #FP_PARAMS, FP_RULES) WITH OVERVIEW;

SELECT * FROM FP_RULES ORDER BY LIFT DESC;
