SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_RGP_DATA;
DROP TYPE PAL_T_RGP_RESULTS;
DROP TABLE PAL_RGP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_RGP');
DROP TABLE RGP_DATA;
DROP TABLE RGP_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_RGP_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE);
CREATE TYPE PAL_T_RGP_RESULTS AS TABLE (ID INTEGER, JOB VARCHAR(60), CONFIDENCE DOUBLE);

CREATE COLUMN TABLE PAL_RGP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_RGP_SIGNATURE VALUES (1, 'PAL.PAL_T_RGP_DATA', 'in');
INSERT INTO PAL_RGP_SIGNATURE VALUES (2, 'PAL.PAL_T_RG_PARAMS', 'in');
INSERT INTO PAL_RGP_SIGNATURE VALUES (3, 'PAL.PAL_T_RG_MODEL', 'in');
--INSERT INTO PAL_RGP_SIGNATURE VALUES (3, 'PAL.PAL_T_RG_PMML', 'in');
INSERT INTO PAL_RGP_SIGNATURE VALUES (4, 'PAL.PAL_T_RGP_RESULTS', 'out');

GRANT SELECT ON PAL_RG_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_RGP', 'AFLPAL', 'LRMCTE', PAL_RGP_SIGNATURE);

-- app setup
CREATE COLUMN TABLE RGP_DATA LIKE PAL_T_RGP_DATA;
CREATE COLUMN TABLE RGP_RESULTS LIKE PAL_T_RGP_RESULTS;

-- app runtime
DROP TABLE #RG_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #RG_PARAMS LIKE PAL_T_RG_PARAMS;
INSERT INTO #RG_PARAMS VALUES ('MODEL_TYPE', 1, null, null); -- 1: table, 2: PMML

TRUNCATE TABLE RGP_DATA;
INSERT INTO RGP_DATA VALUES (1,3020,2600);
INSERT INTO RGP_DATA VALUES (2,5300,2020);

TRUNCATE TABLE RGP_RESULTS;

CALL _SYS_AFL.PAL_RGP (RGP_DATA, #RG_PARAMS, RG_MODEL, RGP_RESULTS) WITH OVERVIEW;
--CALL _SYS_AFL.PAL_RGP (RGP_DATA, #RG_PARAMS, RG_PMML, RGP_RESULTS) WITH OVERVIEW;

SELECT * FROM RGP_RESULTS;
