SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_AH_DATA;
DROP TYPE PAL_T_AH_PARAMS;
DROP TYPE PAL_T_AH_COMBINE;
DROP TYPE PAL_T_AH_RESULTS;
DROP TABLE PAL_AH_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_AH');
DROP VIEW V_AH_DATA;
DROP TABLE AH_COMBINE;
DROP TABLE AH_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_AH_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_AH_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_AH_COMBINE AS TABLE (STAGE INTEGER, CLUSTER_A INTEGER, CLUSTER_B INTEGER, DISTANCE DOUBLE);
CREATE TYPE PAL_T_AH_RESULTS AS TABLE (ID INTEGER, CLUSTER_NUMBER INTEGER);

CREATE COLUMN TABLE PAL_AH_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_AH_SIGNATURE VALUES (1, 'PAL.PAL_T_AH_DATA', 'in');
INSERT INTO PAL_AH_SIGNATURE VALUES (2, 'PAL.PAL_T_AH_PARAMS', 'in');
INSERT INTO PAL_AH_SIGNATURE VALUES (3, 'PAL.PAL_T_AH_COMBINE', 'out');
INSERT INTO PAL_AH_SIGNATURE VALUES (4, 'PAL.PAL_T_AH_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_AH', 'AFLPAL', 'HCAGGLOMERATE', PAL_AH_SIGNATURE);

-- app setup
CREATE VIEW V_AH_DATA AS 
	SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE AH_COMBINE LIKE PAL_T_AH_COMBINE;
CREATE COLUMN TABLE AH_RESULTS LIKE PAL_T_AH_RESULTS;

-- app runtime
DROP TABLE #AH_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #AH_PARAMS LIKE PAL_T_AH_PARAMS;
INSERT INTO #AH_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #AH_PARAMS VALUES ('CLUSTER_NUM', 3, null, null);
-- Distance: 1:Manhattan, 2:Euclidean, 3:Minkowski, 4:Chebyshev, 6: Cosine, 7:Pearson, 8:Squared Euclidian, 9:Jaccard
INSERT INTO #AH_PARAMS VALUES ('DISTANCE_FUNC', 8, null, null); 
-- Method: 1: Nearest Neighbor, 2:Farthest Neighbor, 3:Group Avg, 4:Weighted Avg, 5:Centroid, 6:Median; 7:Ward
INSERT INTO #AH_PARAMS VALUES ('CLUSTER_METHOD', 5, null, null);
--INSERT INTO #AH_PARAMS VALUES ('DISTANCE_DIMENSION', null, 3.0, null); -- with Minkowski
--INSERT INTO #AH_PARAMS VALUES ('NORMALIZE_TYPE', 0, null, null); -- 0,1,2,3

TRUNCATE TABLE AH_COMBINE;
TRUNCATE TABLE AH_RESULTS;

CALL _SYS_AFL.PAL_AH (V_AH_DATA, #AH_PARAMS, AH_COMBINE, AH_RESULTS) WITH OVERVIEW;

SELECT * FROM V_AH_DATA;
SELECT * FROM AH_COMBINE;
SELECT * FROM AH_RESULTS;
SELECT a.ID, b.CUSTOMER, b.LIFESPEND, b.NEWSPEND, b.INCOME, b.LOYALTY, CLUSTER_NUMBER 
	FROM AH_RESULTS a, CUSTOMERS b 
	WHERE a.ID = b.ID
	;
