SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_SV_DATA;
DROP TYPE PAL_T_SV_PARAMS;
DROP TYPE PAL_T_SV_MODEL1;
DROP TYPE PAL_T_SV_MODEL2;
DROP TABLE PAL_SV_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_SV');
DROP TABLE SV_MODEL1;
DROP TABLE SV_MODEL2;

-- PAL setup
CREATE TYPE PAL_T_SV_DATA AS TABLE (ID INTEGER, FRAUD INTEGER, POLICY INTEGER, AGE INTEGER, AMOUNT INTEGER, OCCUPATION INTEGER);
CREATE TYPE PAL_T_SV_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SV_MODEL1 AS TABLE (NAME VARCHAR(50), VALUE DOUBLE);
CREATE TYPE PAL_T_SV_MODEL2 AS TABLE (ID INTEGER, ALPHA DOUBLE, POLICY INTEGER, AGE INTEGER, AMOUNT INTEGER, OCCUPATION INTEGER);

CREATE COLUMN TABLE PAL_SV_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SV_SIGNATURE VALUES (1, 'PAL.PAL_T_SV_DATA', 'in');
INSERT INTO PAL_SV_SIGNATURE VALUES (2, 'PAL.PAL_T_SV_PARAMS', 'in');
INSERT INTO PAL_SV_SIGNATURE VALUES (3, 'PAL.PAL_T_SV_MODEL1', 'out');
INSERT INTO PAL_SV_SIGNATURE VALUES (4, 'PAL.PAL_T_SV_MODEL2', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SV', 'AFLPAL', 'SVMTRAIN', PAL_SV_SIGNATURE);

-- app setup
CREATE COLUMN TABLE SV_MODEL1 LIKE PAL_T_SV_MODEL1;
CREATE COLUMN TABLE SV_MODEL2 LIKE PAL_T_SV_MODEL2;

-- app runtime
DROP TABLE #SV_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #SV_PARAMS LIKE PAL_T_SV_PARAMS;
INSERT INTO #SV_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #SV_PARAMS VALUES ('KERNEL_TYPE', 2, null, null);
INSERT INTO #SV_PARAMS VALUES ('TYPE', 1, null, null);
--INSERT INTO #SV_PARAMS VALUES ('CROSS_VALIDATION', 0, null, null);
--INSERT INTO #SV_PARAMS VALUES ('NR_FOLD', 5, null, null);

TRUNCATE TABLE SV_MODEL1;
TRUNCATE TABLE SV_MODEL2;

CALL _SYS_AFL.PAL_SV (FRAUD, #SV_PARAMS, SV_MODEL1, SV_MODEL2) WITH OVERVIEW;

SELECT * FROM SV_MODEL1;
SELECT * FROM SV_MODEL2;
