-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_CENTERS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_KMEDIANS');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP TABLE "CENTERS";
DROP VIEW "V_RESULTS";
DROP VIEW "V_CENTERS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "LIFESPEND" DOUBLE, "NEWSPEND" DOUBLE, "INCOME" DOUBLE, "LOYALTY" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "CENTER_ID" INTEGER, "DISTANCE" DOUBLE);
CREATE TYPE "T_CENTERS" AS TABLE ("CENTER_ID" INTEGER, "LIFESPEND" DOUBLE, "NEWSPEND" DOUBLE, "INCOME" DOUBLE, "LOYALTY" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_CENTERS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'KMEDIANS', 'DEVUSER', 'P_KMEDIANS', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "ID", "LIFESPEND", "NEWSPEND", "INCOME", "LOYALTY"
		FROM "PAL"."CUSTOMERS"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "CENTERS" LIKE "T_CENTERS";
CREATE VIEW "V_RESULTS" AS
	SELECT a."ID", b."CUSTOMER", b."LIFESPEND", b."NEWSPEND", b."INCOME", b."LOYALTY", a."CENTER_ID" + 1 AS "CLUSTER_NUMBER" 
		FROM "RESULTS" a, "PAL"."CUSTOMERS" b 
		WHERE a."ID" = b."ID"
	;
CREATE VIEW "V_CENTERS" AS
	SELECT "CENTER_ID" + 1 AS "CLUSTER_NUMBER", "LIFESPEND", "NEWSPEND", "INCOME", "LOYALTY"
		FROM "CENTERS" 
	;

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('GROUP_NUMBER', 3, null, null);
INSERT INTO "#PARAMS" VALUES ('INIT_TYPE', 4, null, null);
INSERT INTO "#PARAMS" VALUES ('DISTANCE_LEVEL', 2, null, null);
INSERT INTO "#PARAMS" VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO "#PARAMS" VALUES ('NORMALIZATION', 0, null, null);
INSERT INTO "#PARAMS" VALUES ('EXIT_THRESHOLD', null, 0.0001, null);
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "CENTERS";

CALL "P_KMEDIANS" ("V_DATA", "#PARAMS", "RESULTS", "CENTERS") WITH OVERVIEW;

SELECT * FROM "V_RESULTS";
SELECT * FROM "V_CENTERS";
