-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_MODEL";
DROP TYPE "T_IMPORTANCE";
DROP TYPE "T_ERROR";
DROP TYPE "T_CONFUSION";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_RF_M');
DROP VIEW "V_DATA";
DROP TABLE "MODEL";
DROP TABLE "IMPORTANCE";
DROP TABLE "ERROR";
DROP TABLE "CONFUSION";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("POLICY" NVARCHAR(10), "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" NVARCHAR(10), "FRAUD" NVARCHAR(10));
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_MODEL" AS TABLE ("ID" INTEGER, "TREEINDEX" INTEGER, "MODEL" VARCHAR(5000));
CREATE TYPE "T_IMPORTANCE" AS TABLE ("VARIABLE" VARCHAR(100), "IMPORTANCE" DOUBLE);
CREATE TYPE "T_ERROR" AS TABLE ("TREEINDEX" INTEGER, "ERROR_RATE" DOUBLE);
CREATE TYPE "T_CONFUSION" AS TABLE ("ID" INTEGER, "CONTENT" VARCHAR(1000));
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_MODEL', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_IMPORTANCE', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_ERROR', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_CONFUSION', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'RANDOMFORESTTRAIN', 'DEVUSER', 'P_RF_M', "SIGNATURE");

-- data setup
CREATE VIEW "V_DATA" AS SELECT "POLICY", "AGE", "AMOUNT", "OCCUPATION", "FRAUD" FROM "PAL"."CLAIMS";
CREATE COLUMN TABLE "MODEL" LIKE "T_MODEL";
CREATE COLUMN TABLE "IMPORTANCE" LIKE "T_IMPORTANCE";
CREATE COLUMN TABLE "ERROR" LIKE "T_ERROR";
CREATE COLUMN TABLE "CONFUSION" LIKE "T_CONFUSION";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('TREES_NUM', 300, null, null); 	-- default: 500
INSERT INTO "#PARAMS" VALUES ('TRY_NUM', 3, null, null);	 	-- default: sqrt(nr.dependent variables) when classification
INSERT INTO "#PARAMS" VALUES ('CONTINUOUS_COL', 1, null, null); -- specify column # as continuous (default for integer columns is categorical)
INSERT INTO "#PARAMS" VALUES ('CONTINUOUS_COL', 2, null, null); -- specify column # as continuous (default for integer columns is categorical)

TRUNCATE TABLE "MODEL";
TRUNCATE TABLE "IMPORTANCE";
TRUNCATE TABLE "ERROR";
TRUNCATE TABLE "CONFUSION";

CALL "P_RF_M" ("V_DATA", "#PARAMS", "MODEL", "IMPORTANCE", "ERROR", "CONFUSION") WITH OVERVIEW;

SELECT * FROM "MODEL";
SELECT * FROM "IMPORTANCE";
SELECT * FROM "ERROR";
SELECT * FROM "CONFUSION";
