SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_KM_V_TYPE_ASSIGN AS TABLE (ID INTEGER, TYPE_ASSIGN INTEGER);
CREATE TYPE PAL_T_KM_V_RESULTS AS TABLE (NAME VARCHAR(50), S DOUBLE);

CREATE COLUMN TABLE PAL_KM_V_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_KM_V_SIGNATURE VALUES (1, 'PAL.PAL_T_KM_DATA', 'in');
INSERT INTO PAL_KM_V_SIGNATURE VALUES (2, 'PAL.PAL_T_KM_V_TYPE_ASSIGN', 'in');
INSERT INTO PAL_KM_V_SIGNATURE VALUES (3, 'PAL.PAL_T_KM_PARAMS', 'in');
INSERT INTO PAL_KM_V_SIGNATURE VALUES (4, 'PAL.PAL_T_KM_V_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_KM_V', 'AFLPAL', 'VALIDATEKMEANS', PAL_KM_V_SIGNATURE);

-- app setup

CREATE VIEW V_KM_TYPE_ASSIGN AS 
	SELECT ID, CENTER_ID AS TYPE_ASSIGN 
		FROM KM_RESULTS
	;
CREATE COLUMN TABLE KM_V_PARAMS LIKE PAL_T_KM_PARAMS;
CREATE COLUMN TABLE KM_V_RESULTS LIKE PAL_T_KM_V_RESULTS;

INSERT INTO KM_V_PARAMS VALUES ('VARIABLE_NUM', 4, null, null);
INSERT INTO KM_V_PARAMS VALUES ('THREAD_NUMBER', 1, null, null);

-- app runtime

TRUNCATE TABLE KM_V_RESULTS;

CALL _SYS_AFL.PAL_KM_V (V_KM_DATA, V_KM_TYPE_ASSIGN, KM_V_PARAMS, KM_V_RESULTS) WITH OVERVIEW;
