SET SCHEMA PAL; 

-- PAL setup

CREATE TYPE PAL_T_KNN_DATA AS TABLE (CUSTOMER_ID INTEGER, GENDER INTEGER, LIFESPEND INTEGER, NEWSPEND INTEGER);
CREATE TYPE PAL_T_KNN_CLASS AS TABLE (CUSTOMER_ID INTEGER, LIFESPEND INTEGER, NEWSPEND INTEGER);
CREATE TYPE PAL_T_KNN_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_KNN_PREDICT AS TABLE (CUSTOMER_ID INTEGER, GENDER INTEGER);

CREATE COLUMN TABLE PAL_KNN_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_KNN_SIGNATURE VALUES (1, 'PAL.PAL_T_KNN_DATA', 'in');
INSERT INTO PAL_KNN_SIGNATURE VALUES (2, 'PAL.PAL_T_KNN_CLASS', 'in');
INSERT INTO PAL_KNN_SIGNATURE VALUES (3, 'PAL.PAL_T_KNN_PARAMS', 'in');
INSERT INTO PAL_KNN_SIGNATURE VALUES (4, 'PAL.PAL_T_KNN_PREDICT', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_KNN', 'AFLPAL', 'KNN', PAL_KNN_SIGNATURE);

-- app setup
CREATE VIEW V_KNN_DATA AS 
	SELECT c.CUSTOMER_ID, c.CUSTOMER_GENDER_ID AS GENDER, l.LIFESPEND, n.NEWSPEND
	 FROM CUSTOMER c
	 INNER JOIN (
			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS LIFESPEND
			 FROM ORDER_FACTS
			 GROUP BY CUSTOMER_ID
				) l ON(c.CUSTOMER_ID = l.CUSTOMER_ID)
	 INNER JOIN (
 			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS NEWSPEND
			 FROM ORDER_FACTS
			 WHERE CALENDAR_ID=23
			 GROUP BY CUSTOMER_ID
				) n ON(c.CUSTOMER_ID = n.CUSTOMER_ID)
	 ;
CREATE COLUMN TABLE KNN_CLASS LIKE PAL_T_KNN_CLASS;
CREATE COLUMN TABLE KNN_PARAMS LIKE PAL_T_KNN_PARAMS;
CREATE COLUMN TABLE KNN_PREDICT LIKE PAL_T_KNN_PREDICT;

INSERT INTO KNN_CLASS VALUES (1,3020,1300);
INSERT INTO KNN_CLASS VALUES (2,5300,980);

INSERT INTO KNN_PARAMS VALUES ('THREAD_NUMBER', 4, null, null);
INSERT INTO KNN_PARAMS VALUES ('ATTRIBUTE_NUM', 2, null, null);
INSERT INTO KNN_PARAMS VALUES ('K_NEAREST_NEIGHBOURS', 3, null, null);
INSERT INTO KNN_PARAMS VALUES ('VOTING_TYPE', 0, null, null); -- 0=majority, 1=distance-weighted

-- app runtime

--UPDATE KNN_PARAMS SET INTARGS=10 WHERE NAME='K_NEAREST_NEIGHBOURS';
--UPDATE KNN_PARAMS SET INTARGS=1 WHERE NAME='VOTING_TYPE';

TRUNCATE TABLE KNN_PREDICT;

CALL _SYS_AFL.PAL_KNN (V_KNN_DATA, KNN_CLASS, KNN_PARAMS, KNN_PREDICT) WITH OVERVIEW;

SELECT * FROM KNN_PREDICT;
