SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_DP_DATA;
DROP TYPE PAL_T_DP_DIST;
DROP TYPE PAL_T_DP_PARAMS;
DROP TYPE PAL_T_DP_RESULTS;
DROP TABLE PAL_DP_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_DP');
DROP TABLE DP_DATA;
DROP TABLE DP_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_DP_DATA AS TABLE (VALUE DOUBLE);
CREATE TYPE PAL_T_DP_DIST AS TABLE (NAME VARCHAR(60), VALUE VARCHAR(60));
CREATE TYPE PAL_T_DP_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_DP_RESULTS AS TABLE (VALUE DOUBLE, PROBABILITY DOUBLE);

CREATE COLUMN TABLE PAL_DP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_DP_SIGNATURE VALUES (1, 'PAL.PAL_T_DP_DATA', 'in');
INSERT INTO PAL_DP_SIGNATURE VALUES (2, 'PAL.PAL_T_DP_DIST', 'in');
INSERT INTO PAL_DP_SIGNATURE VALUES (3, 'PAL.PAL_T_DP_PARAMS', 'in');
INSERT INTO PAL_DP_SIGNATURE VALUES (4, 'PAL.PAL_T_DP_RESULTS', 'out');

GRANT SELECT ON PAL_DP_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_DP', 'AFLPAL', 'DISTRPROB', PAL_DP_SIGNATURE);

-- app setup
CREATE TABLE DP_DATA LIKE PAL_T_DP_DATA;
INSERT INTO DP_DATA VALUES (50);
INSERT INTO DP_DATA VALUES (100);
INSERT INTO DP_DATA VALUES (150);
INSERT INTO DP_DATA VALUES (200);
INSERT INTO DP_DATA VALUES (250);
INSERT INTO DP_DATA VALUES (300);
INSERT INTO DP_DATA VALUES (350);
INSERT INTO DP_DATA VALUES (400);
INSERT INTO DP_DATA VALUES (450);
INSERT INTO DP_DATA VALUES (500);
INSERT INTO DP_DATA VALUES (550);
INSERT INTO DP_DATA VALUES (600);
INSERT INTO DP_DATA VALUES (650);
CREATE COLUMN TABLE DP_RESULTS LIKE PAL_T_DP_RESULTS;

-- app runtime
DROP TABLE #DP_DIST;
CREATE LOCAL TEMPORARY COLUMN TABLE #DP_DIST LIKE PAL_T_DP_DIST;
INSERT INTO #DP_DIST VALUES ('DISTRIBUTIONNAME', 'WEIBULL'); -- uniform, normal, weibull, gamma
INSERT INTO #DP_DIST VALUES ('MIN', '0'); -- uniform
INSERT INTO #DP_DIST VALUES ('MAX', '1'); -- uniform
INSERT INTO #DP_DIST VALUES ('MEAN', '0'); -- normal
INSERT INTO #DP_DIST VALUES ('VARIANCE', '1'); -- normal
INSERT INTO #DP_DIST VALUES ('SHAPE', '2.06698'); -- weibull, gamma
INSERT INTO #DP_DIST VALUES ('SCALE', '244.401'); -- weibull, gamma

DROP TABLE #DP_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #DP_PARAMS LIKE PAL_T_DP_PARAMS;
INSERT INTO #DP_PARAMS VALUES ('LOWER_UPPER', 0, null, null); -- 0: CDF, 1: CCDF

TRUNCATE TABLE DP_RESULTS;

CALL _SYS_AFL.PAL_DP (DP_DATA, #DP_DIST, #DP_PARAMS, DP_RESULTS) WITH OVERVIEW;

SELECT * FROM DP_RESULTS;
