SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_RG_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, INCOME DOUBLE);
CREATE TYPE PAL_T_RG_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_RG_COEFF AS TABLE (ID INTEGER, AI DOUBLE);
CREATE TYPE PAL_T_RG_FITTED AS TABLE (ID INTEGER, FITTED DOUBLE);
CREATE TYPE PAL_T_RG_SIGNIFICANCE AS TABLE (NAME VARCHAR(50), VALUE DOUBLE);
CREATE TYPE PAL_T_RG_PMML AS TABLE (ID INTEGER, PMML VARCHAR(5000));

CREATE COLUMN TABLE PAL_RG_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_RG_SIGNATURE VALUES (1, 'PAL.PAL_T_RG_DATA', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (2, 'PAL.PAL_T_RG_PARAMS', 'in');
INSERT INTO PAL_RG_SIGNATURE VALUES (3, 'PAL.PAL_T_RG_COEFF', 'out');
INSERT INTO PAL_RG_SIGNATURE VALUES (4, 'PAL.PAL_T_RG_FITTED', 'out');
INSERT INTO PAL_RG_SIGNATURE VALUES (5, 'PAL.PAL_T_RG_SIGNIFICANCE', 'out');
INSERT INTO PAL_RG_SIGNATURE VALUES (6, 'PAL.PAL_T_RG_PMML', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_RG', 'AFLPAL', 'LNREGRESSION', PAL_RG_SIGNATURE);

-- app setup

CREATE VIEW V_RG_DATA AS 
	SELECT ID, LIFESPEND, INCOME
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE RG_PARAMS LIKE PAL_T_RG_PARAMS;
CREATE COLUMN TABLE RG_COEFF LIKE PAL_T_RG_COEFF;
CREATE COLUMN TABLE RG_FITTED LIKE PAL_T_RG_FITTED;
CREATE COLUMN TABLE RG_SIGNIFICANCE LIKE PAL_T_RG_SIGNIFICANCE;
CREATE COLUMN TABLE RG_PMML LIKE PAL_T_RG_PMML;

CREATE VIEW V_RG_FITTED AS
	SELECT a.ID, b.LIFESPEND, ROUND(a.FITTED,1) AS LIFESPEND_FITTED, b.INCOME 
		FROM RG_FITTED a, V_RG_DATA b 
		WHERE a.ID = b.ID
	;

INSERT INTO RG_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO RG_PARAMS VALUES ('VARIABLE_NUM', 1, null, null);
INSERT INTO RG_PARAMS VALUES ('PMML_EXPORT', 2, null, null);

-- app runtime

--UPDATE RG_PARAMS SET INTARGS=1 WHERE NAME='VARIABLE_NUM';

TRUNCATE TABLE RG_COEFF;
TRUNCATE TABLE RG_FITTED;
TRUNCATE TABLE RG_SIGNIFICANCE;
TRUNCATE TABLE RG_PMML;

CALL _SYS_AFL.PAL_RG (V_RG_DATA, RG_PARAMS, RG_COEFF, RG_FITTED, RG_SIGNIFICANCE, RG_PMML) WITH OVERVIEW;


