-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_TT');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";


-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("INCOME" DOUBLE, "LOYALTY" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("NAME" VARCHAR(60), "VALUE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'TTEST', 'DEVUSER', 'P_TT', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "INCOME", "LOYALTY"
		FROM "PAL"."CUSTOMERS"
	;
CREATE TABLE "RESULTS" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('TEST_TYPE', 0, null, null); -- 0: two sides, 1:less, 2: greater (default:0)
INSERT INTO "#PARAMS" VALUES ('MU', null, 3.0, null); -- default 0
INSERT INTO "#PARAMS" VALUES ('PAIRED', 0, null, null); -- 0: no, 1: yes (default:0)
INSERT INTO "#PARAMS" VALUES ('VAR_EQUAL', 0, null, null); -- 0: no, 1: yes (default:0)
INSERT INTO "#PARAMS" VALUES ('CONF_LEVEL', null, 0.95, null); -- default 0.95

TRUNCATE TABLE "RESULTS";

CALL "P_TT" ("V_DATA", "#PARAMS", "RESULTS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
