SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_CB_DATA;
DROP TYPE PAL_T_CB_PARAMS;
DROP TYPE PAL_T_CB_RESULTS;
DROP TABLE PAL_CB_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_CB');
DROP VIEW V_CB_DATA;
DROP TABLE CB_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_CB_DATA AS TABLE (ID INTEGER, POLICY NVARCHAR(10));
CREATE TYPE PAL_T_CB_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_CB_RESULTS AS TABLE (ID INTEGER, IS_HOME INTEGER, IS_TRAVEL INTEGER, IS_VEHICLE INTEGER);

CREATE COLUMN TABLE PAL_CB_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_CB_SIGNATURE VALUES (1, 'PAL.PAL_T_CB_DATA', 'in');
INSERT INTO PAL_CB_SIGNATURE VALUES (2, 'PAL.PAL_T_CB_PARAMS', 'in');
INSERT INTO PAL_CB_SIGNATURE VALUES (3, 'PAL.PAL_T_CB_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_CB', 'AFLPAL', 'CONV2BINARYVECTOR', PAL_CB_SIGNATURE);

-- app setup

CREATE VIEW V_CB_DATA AS 
	SELECT ID, POLICY 
		FROM CLAIMS
		ORDER BY POLICY
	;
CREATE COLUMN TABLE CB_RESULTS LIKE PAL_T_CB_RESULTS;

-- app runtime

DROP TABLE #CB_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #CB_PARAMS LIKE PAL_T_CB_PARAMS;
INSERT INTO #CB_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #CB_PARAMS VALUES ('OUT_PUT_COLUMNS', 4, null, null);

TRUNCATE TABLE CB_RESULTS;

CALL _SYS_AFL.PAL_CB (V_CB_DATA, #CB_PARAMS, CB_RESULTS) WITH OVERVIEW;

SELECT * FROM V_CB_DATA;
SELECT * FROM CB_RESULTS;
