SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_DT_DATA;
DROP TYPE PAL_T_DT_PARAMS;
DROP TYPE PAL_T_DT_MODEL;
DROP TYPE PAL_T_DT_STATS;
DROP TABLE PAL_DT_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_DT');
DROP VIEW V_DT_DATA;
DROP TABLE DT_MODEL;
DROP TABLE DT_STATS;

-- PAL setup
CREATE TYPE PAL_T_DT_DATA AS TABLE (POLICY VARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION VARCHAR(10), FRAUD VARCHAR(10));
CREATE TYPE PAL_T_DT_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_DT_MODEL AS TABLE (ID INTEGER, MODEL VARCHAR(5000));
CREATE TYPE PAL_T_DT_STATS AS TABLE (FRAUD1 VARCHAR(50), FRAUD2 VARCHAR(50), NUM_ROWS INTEGER);

CREATE COLUMN TABLE PAL_DT_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_DT_SIGNATURE VALUES (1, 'PAL.PAL_T_DT_DATA', 'in');
INSERT INTO PAL_DT_SIGNATURE VALUES (2, 'PAL.PAL_T_DT_PARAMS', 'in');
INSERT INTO PAL_DT_SIGNATURE VALUES (3, 'PAL.PAL_T_DT_MODEL', 'out');
INSERT INTO PAL_DT_SIGNATURE VALUES (4, 'PAL.PAL_T_DT_STATS', 'out');

GRANT SELECT ON PAL_DT_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_DT', 'AFLPAL', 'CART', PAL_DT_SIGNATURE);

-- app setup
CREATE VIEW V_DT_DATA AS
 SELECT POLICY, AGE, AMOUNT, OCCUPATION, FRAUD 
  FROM CLAIMS
  ;
CREATE COLUMN TABLE DT_MODEL LIKE PAL_T_DT_MODEL;
CREATE COLUMN TABLE DT_STATS LIKE PAL_T_DT_STATS;

-- app runtime
DROP TABLE #DT_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #DT_PARAMS LIKE PAL_T_DT_PARAMS;
INSERT INTO #DT_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #DT_PARAMS VALUES ('SPLIT_CRITERIA', 103, null, null);
INSERT INTO #DT_PARAMS VALUES ('SPLIT_THRESHOLD', null, 0.05, null);
INSERT INTO #DT_PARAMS VALUES ('MAX_DEPTH', 4, null, null);
INSERT INTO #DT_PARAMS VALUES ('MIN_NUMS_RECORDS', 1, null, null);
INSERT INTO #DT_PARAMS VALUES ('CONTINUOUS_COL', 1, 30, null);
INSERT INTO #DT_PARAMS VALUES ('CONTINUOUS_COL', 1, 50, null);
INSERT INTO #DT_PARAMS VALUES ('CONTINUOUS_COL', 2, 500, null);
INSERT INTO #DT_PARAMS VALUES ('CONTINUOUS_COL', 2, 1000, null);
INSERT INTO #DT_PARAMS VALUES ('CONTINUOUS_COL', 2, 2000, null);
INSERT INTO #DT_PARAMS VALUES ('IS_OUTPUT_RULES', 0, null, null);
INSERT INTO #DT_PARAMS VALUES ('IS_SPLIT_MODEL', 1, null, null);
INSERT INTO #DT_PARAMS VALUES ('PMML_EXPORT', 0, null, null);

TRUNCATE TABLE DT_MODEL;
TRUNCATE TABLE DT_STATS;

CALL _SYS_AFL.PAL_DT (V_DT_DATA, #DT_PARAMS, DT_MODEL, DT_STATS) WITH OVERVIEW;

SELECT * FROM DT_MODEL;
SELECT * FROM DT_STATS;
