-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_SERIES";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_TT');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP TABLE "SERIES";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("CALENDAR_ID" INTEGER, "SALES_AMOUNT" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("TREND" INTEGER);
CREATE TYPE "T_SERIES" AS TABLE ("ID" INTEGER, "VALUE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_SERIES', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'TRENDTEST', 'DEVUSER', 'P_TT', "SIGNATURE");

-- data setup
CREATE VIEW "V_DATA" AS 
	SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		FROM "PAL"."ORDER_FACTS"
		WHERE "ITEM_ID" BETWEEN 0 AND 9
		GROUP BY "CALENDAR_ID" 
		ORDER BY "CALENDAR_ID"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "SERIES" LIKE "T_SERIES";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('METHOD', 1, null, null); -- 1: MK test; 2: Difference-sign test
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.05, null); -- Tolerance probability for MK test

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "SERIES";

CALL "P_TT" ("V_DATA", "#PARAMS", "RESULTS", "SERIES") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "SERIES";
