SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_NB_DATA;
DROP TYPE PAL_T_NB_PARAMS;
DROP TYPE PAL_T_NB_MODEL;
DROP TABLE PAL_NB_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_NB');
DROP VIEW V_NB_DATA;
DROP TABLE NB_MODEL;

-- PAL setup
CREATE TYPE PAL_T_NB_DATA AS TABLE (POLICY VARCHAR(10), AGE INTEGER, AMOUNT INTEGER, OCCUPATION VARCHAR(10), FRAUD VARCHAR(10));
CREATE TYPE PAL_T_NB_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_NB_MODEL AS TABLE (ID INTEGER, JSONMODEL VARCHAR(5000));

CREATE COLUMN TABLE PAL_NB_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_NB_SIGNATURE VALUES (1, 'PAL.PAL_T_NB_DATA', 'in');
INSERT INTO PAL_NB_SIGNATURE VALUES (2, 'PAL.PAL_T_NB_PARAMS', 'in');
INSERT INTO PAL_NB_SIGNATURE VALUES (3, 'PAL.PAL_T_NB_MODEL', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_NB', 'AFLPAL', 'NBCTRAIN', PAL_NB_SIGNATURE);

-- app setup
CREATE VIEW V_NB_DATA AS
 SELECT POLICY, AGE, AMOUNT, OCCUPATION, FRAUD 
  FROM CLAIMS
  ;
CREATE COLUMN TABLE NB_MODEL LIKE PAL_T_NB_MODEL;

-- app runtime
DROP TABLE #NB_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #NB_PARAMS LIKE PAL_T_NB_PARAMS;
INSERT INTO #NB_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #NB_PARAMS VALUES ('IS_SPLIT_MODEL', 0, null, null);
INSERT INTO #NB_PARAMS VALUES ('LAPLACE', null, 0.01, null);

TRUNCATE TABLE NB_MODEL;

CALL _SYS_AFL.PAL_NB (V_NB_DATA, #NB_PARAMS, NB_MODEL) WITH OVERVIEW;

SELECT * FROM NB_MODEL;
