-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_STATS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_SES');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";
DROP TABLE "STATS";
DROP VIEW "V_RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("CALENDAR_ID" INTEGER, "SALES_AMOUNT" INTEGER);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_RESULTS" AS TABLE ("CALENDAR_ID" INTEGER, "SALES_AMOUNT" INTEGER, "L1" INTEGER, "U1" INTEGER, "L2" INTEGER, "U2" INTEGER);
CREATE TYPE "T_STATS" AS TABLE ("NAME" VARCHAR(60), "VALUE" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_STATS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'SINGLESMOOTH', 'DEVUSER', 'P_SES', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "CALENDAR_ID", SUM("SALES_AMOUNT") AS "SALES_AMOUNT"
		FROM "PAL"."ORDER_FACTS"
		WHERE "ITEM_ID" BETWEEN 0 AND 9
		GROUP BY "CALENDAR_ID" 
		ORDER BY "CALENDAR_ID"
	;
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "STATS" LIKE "T_STATS";
CREATE VIEW "V_RESULTS" AS
	SELECT 
		CASE WHEN a."CALENDAR_ID" IS NOT NULL THEN a."CALENDAR_ID" ELSE b."CALENDAR_ID" END AS "CALENDAR_ID", 
		a."SALES_AMOUNT", 
		ROUND(b."SALES_AMOUNT") AS "SALES_AMOUNT_PREDICTED",
		b."L1", b."U1", b."L2", b."U2"
	 FROM "V_DATA" a 
	 FULL JOIN "RESULTS" b ON (a."CALENDAR_ID"=b."CALENDAR_ID")
	 ORDER BY 1 
	 ;

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('ADAPTIVE_METHOD', 1, null, null); -- 0 : single exponential smoothing; 1 : adaptive-response-rate
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.1, null);
INSERT INTO "#PARAMS" VALUES ('DELTA', null, 0.2, null); -- when adaptive-response-rate
INSERT INTO "#PARAMS" VALUES ('FORECAST_NUM', 6, null, null);
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MPE'); 
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MSE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'RMSE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'ET');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MAD'); 
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MASE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'WMAPE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'SMAPE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MAPE');
INSERT INTO "#PARAMS" VALUES ('EXPOST_FLAG', 1, null, null); -- 0 : do not output; 1 : output expost forecast
INSERT INTO "#PARAMS" VALUES ('PREDICTION_CONFIDENCE_1', null, 0.8, null);
INSERT INTO "#PARAMS" VALUES ('PREDICTION_CONFIDENCE_2', null, 0.95, null);

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "STATS";

CALL "P_SES" ("V_DATA", "#PARAMS", "RESULTS", "STATS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "STATS";
SELECT * FROM "V_RESULTS";
