SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_TS_DATA;
DROP TYPE PAL_T_TS_PARAMS;
DROP TYPE PAL_T_TS_MODEL;
DROP TABLE PAL_TS_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_TS');
DROP TABLE TS_MODEL;

-- PAL setup
CREATE TYPE PAL_T_TS_DATA AS TABLE (ID INTEGER, PRICE DOUBLE);
CREATE TYPE PAL_T_TS_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_TS_MODEL AS TABLE (NAME VARCHAR(60), VALUE VARCHAR(5000));

CREATE COLUMN TABLE PAL_TS_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_TS_SIGNATURE VALUES (1, 'PAL.PAL_T_TS_DATA', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (2, 'PAL.PAL_T_TS_PARAMS', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (3, 'PAL.PAL_T_TS_MODEL', 'out');

GRANT SELECT ON PAL_TS_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_TS', 'AFLPAL', 'ARIMATRAIN', PAL_TS_SIGNATURE);

-- app setup
CREATE COLUMN TABLE TS_MODEL LIKE PAL_T_TS_MODEL;

-- app runtime
DROP TABLE #TS_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #TS_PARAMS LIKE PAL_T_TS_PARAMS;
INSERT INTO #TS_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #TS_PARAMS VALUES ('P', 1, null, null); -- Auto Regression
INSERT INTO #TS_PARAMS VALUES ('D', 0, null, null); -- Integrated
INSERT INTO #TS_PARAMS VALUES ('Q', 1, null, null); -- Moving Average
INSERT INTO #TS_PARAMS VALUES ('METHOD', 1, null, null); -- 0: conditional sum squares, 1: max likelihood estimation
INSERT INTO #TS_PARAMS VALUES ('STATIONARY', 1, null, null); -- 0: result may not be stationary, 1: is stationary

TRUNCATE TABLE TS_MODEL;

CALL _SYS_AFL.PAL_TS (STOCKS, #TS_PARAMS, TS_MODEL) WITH OVERVIEW;

SELECT * FROM TS_MODEL;
