SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_B_DATA AS TABLE (ID INTEGER, INCOME INTEGER);
CREATE TYPE PAL_T_B_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_B_RESULTS AS TABLE (ID INTEGER, INCOME_GROUP INTEGER, PRE_RESULT INTEGER);

CREATE COLUMN TABLE PAL_B_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_B_SIGNATURE VALUES (1, 'PAL.PAL_T_B_DATA', 'in');
INSERT INTO PAL_B_SIGNATURE VALUES (2, 'PAL.PAL_T_B_PARAMS', 'in');
INSERT INTO PAL_B_SIGNATURE VALUES (3, 'PAL.PAL_T_B_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_B', 'AFLPAL', 'BINNING', PAL_B_SIGNATURE);

-- app setup

CREATE COLUMN TABLE B_PARAMS LIKE PAL_T_B_PARAMS;
CREATE COLUMN TABLE B_RESULTS LIKE PAL_T_B_RESULTS;

INSERT INTO B_PARAMS VALUES ('BINNING_METHOD', 0, null, null);
INSERT INTO B_PARAMS VALUES ('SMOOTH_METHOD', 0, null, null);
INSERT INTO B_PARAMS VALUES ('BIN_NUMBER', 3, null, null);
INSERT INTO B_PARAMS VALUES ('BIN_DISTANCE', 25000, null, null); -- used when binning_method = 1
INSERT INTO B_PARAMS VALUES ('SD', 1, null, null);				 -- used when smooth_method = 2

-- app runtime

UPDATE B_PARAMS SET INTARGS=2 WHERE NAME='BINNING_METHOD';
UPDATE B_PARAMS SET INTARGS=1 WHERE NAME='SMOOTH_METHOD';
UPDATE B_PARAMS SET INTARGS=5 WHERE NAME='BIN_NUMBER';

TRUNCATE TABLE B_RESULTS;

CALL _SYS_AFL.PAL_B (CUSTOMERS_INCOME, B_PARAMS, B_RESULTS) WITH OVERVIEW;

-- join to original data
SELECT a.ID, b.INCOME, a.INCOME_GROUP 
 FROM B_RESULTS a 
 INNER JOIN CUSTOMERS_INCOME b ON (a.ID = b.ID)
 ;
