-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_BASIC_INFO";
DROP TYPE "T_PRIOR";
DROP TYPE "T_CLASSIFIER";
DROP TYPE "T_PROJECTION_INFO";
DROP TYPE "T_PROJECTION_MODEL";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_LDAFIT');
DROP VIEW "V_DATA";
DROP TABLE "BASIC_INFO";
DROP TABLE "PRIOR";
DROP TABLE "CLASSIFIER";
DROP TABLE "PROJECTION_INFO";
DROP TABLE "PROJECTION_MODEL";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ATTR1" DOUBLE, "ATTR2" DOUBLE, "ATTR3" DOUBLE, "ATTR4" DOUBLE, "CLASS" VARCHAR(50));
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_BASIC_INFO" AS TABLE ("NAME" VARCHAR(50), "VALUE" INTEGER);
CREATE TYPE "T_PRIOR" AS TABLE ("CLASS" VARCHAR(50), "PRIOR" DOUBLE);
CREATE TYPE "T_CLASSIFIER" AS TABLE ("CLASS" VARCHAR(50), "COEFF1" DOUBLE, "COEFF2" DOUBLE, "COEFF3" DOUBLE, "COEFF4" DOUBLE, "COEFF5" DOUBLE);
CREATE TYPE "T_PROJECTION_INFO" AS TABLE ("PC_ID" VARCHAR(50), "STD_DEV" DOUBLE, "PROPORTION" DOUBLE, "CUMUL_PROPORTION" DOUBLE);
CREATE TYPE "T_PROJECTION_MODEL" AS TABLE ("PC_ID" VARCHAR(50), "WEIGHT1" DOUBLE, "WEIGHT2" DOUBLE, "WEIGHT3" DOUBLE, "WEIGHT4" DOUBLE);
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_BASIC_INFO', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_PRIOR', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_CLASSIFIER', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_PROJECTION_INFO', 'OUT');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_PROJECTION_MODEL', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'LDAFIT', 'DEVUSER', 'P_LDAFIT', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS SELECT "ATTR1", "ATTR2", "ATTR3", "ATTR4", "CLASS" FROM "PAL"."CLASSIFICATION";
CREATE COLUMN TABLE "BASIC_INFO" LIKE "T_BASIC_INFO";
CREATE COLUMN TABLE "PRIOR" LIKE "T_PRIOR";
CREATE COLUMN TABLE "CLASSIFIER" LIKE "T_CLASSIFIER";
CREATE COLUMN TABLE "PROJECTION_INFO" LIKE "T_PROJECTION_INFO";
CREATE COLUMN TABLE "PROJECTION_MODEL" LIKE "T_PROJECTION_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('DO_PROJECTION', 1, null, null); -- 0: no; 1: yes (default:0)
--INSERT INTO "#PARAMS" VALUES ('REGULARIZATION_TYPE', 0, null, null); -- 0:regularized; 1: diagonal; 3: pseudo inverse (default:0)
--INSERT INTO "#PARAMS" VALUES ('REGULARIZATION_AMOUNT', null, 0.0, null); -- only valid when REGULARIZATION_TYPE=0

TRUNCATE TABLE "BASIC_INFO";
TRUNCATE TABLE "PRIOR";
TRUNCATE TABLE "CLASSIFIER";
TRUNCATE TABLE "PROJECTION_INFO";
TRUNCATE TABLE "PROJECTION_MODEL";

CALL "P_LDAFIT" ("V_DATA", "#PARAMS", "BASIC_INFO", "PRIOR", "CLASSIFIER", "PROJECTION_INFO", "PROJECTION_MODEL") WITH OVERVIEW;

SELECT * FROM "BASIC_INFO";
SELECT * FROM "PRIOR";
SELECT * FROM "CLASSIFIER";
SELECT * FROM "PROJECTION_INFO";
SELECT * FROM "PROJECTION_MODEL";
