SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_WT_DATA AS TABLE (ID INTEGER, AGE NVARCHAR(10), SPEND INTEGER);
CREATE TYPE PAL_T_WT_MAP_VALUES AS TABLE (AGE NVARCHAR(60), AGE_VALUE DOUBLE, SPEND INTEGER, SPEND_VALUE DOUBLE);
CREATE TYPE PAL_T_WT_MAP_VARS AS TABLE (WEIGHT DOUBLE, IS_DISCRETE INTEGER, ROW_COUNT INTEGER);
CREATE TYPE PAL_T_WT_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_WT_RESULTS AS TABLE (ID INTEGER, SCORE DOUBLE);

CREATE COLUMN TABLE PAL_WT_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_WT_SIGNATURE VALUES (1, 'PAL.PAL_T_WT_DATA', 'in');
INSERT INTO PAL_WT_SIGNATURE VALUES (2, 'PAL.PAL_T_WT_MAP_VALUES', 'in');
INSERT INTO PAL_WT_SIGNATURE VALUES (3, 'PAL.PAL_T_WT_MAP_VARS', 'in');
INSERT INTO PAL_WT_SIGNATURE VALUES (4, 'PAL.PAL_T_WT_PARAMS', 'in');
INSERT INTO PAL_WT_SIGNATURE VALUES (5, 'PAL.PAL_T_WT_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_WT', 'AFLPAL', 'WEIGHTEDTABLE', PAL_WT_SIGNATURE);

-- app setup

CREATE VIEW V_WT_DATA AS 
	SELECT c.CUSTOMER_ID AS ID, a.CUSTOMER_AGE_NAME AS AGE, l.SPEND
	 FROM CUSTOMER c
	 INNER JOIN CUSTOMER_AGE a ON (a.CUSTOMER_AGE_ID=c.CUSTOMER_AGE_ID)
	 INNER JOIN (
			SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) AS SPEND
			 FROM ORDER_FACTS
			 GROUP BY CUSTOMER_ID
				) l ON(c.CUSTOMER_ID = l.CUSTOMER_ID)
	;
CREATE COLUMN TABLE WT_MAP_VALUES LIKE PAL_T_WT_MAP_VALUES;
CREATE COLUMN TABLE WT_MAP_VARS LIKE PAL_T_WT_MAP_VARS;
CREATE COLUMN TABLE WT_PARAMS LIKE PAL_T_WT_PARAMS;
CREATE COLUMN TABLE WT_RESULTS LIKE PAL_T_WT_RESULTS;

INSERT INTO WT_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);

-- app runtime

TRUNCATE TABLE WT_MAP_VALUES;
INSERT INTO WT_MAP_VALUES VALUES ('20-29', 5.0,    1000, 0.0);
INSERT INTO WT_MAP_VALUES VALUES ('30-39', 4.0,    5000, 1.0);
INSERT INTO WT_MAP_VALUES VALUES ('40-49', 3.0,   10000, 2.0);
INSERT INTO WT_MAP_VALUES VALUES ('50-59', 1.5,   50000, 3.0);
INSERT INTO WT_MAP_VALUES VALUES ('60-69', 0.0,  100000, 4.0);
INSERT INTO WT_MAP_VALUES VALUES (null,    0.0,  200000, 5.0);
INSERT INTO WT_MAP_VALUES VALUES (null,    0.0,  300000, 7.0);

TRUNCATE TABLE WT_MAP_VARS;
INSERT INTO WT_MAP_VARS VALUES (1.5, 1, 5); 
INSERT INTO WT_MAP_VARS VALUES (3.0, 0, 7);

TRUNCATE TABLE WT_RESULTS;

CALL _SYS_AFL.PAL_WT (V_WT_DATA, WT_MAP_VALUES, WT_MAP_VARS, WT_PARAMS, WT_RESULTS) WITH OVERVIEW;

SELECT * FROM WT_MAP_VALUES;
SELECT * FROM WT_MAP_VARS;

SELECT TOP 100 d.*, r.SCORE 
 FROM V_WT_DATA d
 INNER JOIN WT_RESULTS r ON (r.ID=d.ID)
 ORDER BY r.SCORE DESC
 ;
