SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_SOM_DATA AS TABLE (ID INTEGER, LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_SOM_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SOM_MAP AS TABLE (MAP_ID INTEGER, LIFESPEND_WEIGHT DOUBLE, NEWSPEND_WEIGHT DOUBLE, INCOME_WEIGHT DOUBLE, LOYALTY_WEIGHT DOUBLE, ROWCOUNT INTEGER);
CREATE TYPE PAL_T_SOM_RESULTS AS TABLE (ID INTEGER, MAP_ID INTEGER);

CREATE COLUMN TABLE PAL_SOM_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SOM_SIGNATURE VALUES (1, 'PAL.PAL_T_SOM_DATA', 'in');
INSERT INTO PAL_SOM_SIGNATURE VALUES (2, 'PAL.PAL_T_SOM_PARAMS', 'in');
INSERT INTO PAL_SOM_SIGNATURE VALUES (3, 'PAL.PAL_T_SOM_MAP', 'out');
INSERT INTO PAL_SOM_SIGNATURE VALUES (4, 'PAL.PAL_T_SOM_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SOM', 'AFLPAL', 'SELFORGMAP', PAL_SOM_SIGNATURE);

-- app setup

CREATE VIEW V_SOM_DATA AS 
	SELECT ID, LIFESPEND, NEWSPEND, INCOME, LOYALTY 
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE SOM_PARAMS LIKE PAL_T_SOM_PARAMS;
CREATE COLUMN TABLE SOM_MAP LIKE PAL_T_SOM_MAP;
CREATE COLUMN TABLE SOM_RESULTS LIKE PAL_T_SOM_RESULTS;

CREATE VIEW V_SOM_RESULTS AS
	SELECT a.ID, b.CUSTOMER, b.LIFESPEND, b.NEWSPEND, b.INCOME, b.LOYALTY, a.MAP_ID + 1 AS CLUSTER_NUMBER 
		FROM SOM_RESULTS a, CUSTOMERS b 
		WHERE a.ID = b.ID
	;

INSERT INTO SOM_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO SOM_PARAMS VALUES ('SIZE_OF_MAP', 2, null, null);
INSERT INTO SOM_PARAMS VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO SOM_PARAMS VALUES ('NORMALIZATION', 0, null, null); -- 0=none, 1=new range, 2=z-score

-- app runtime

--UPDATE SOM_PARAMS SET INTARGS=3 WHERE NAME='SIZE_OF_MAP';
--UPDATE SOM_PARAMS SET INTARGS=1000 WHERE NAME='MAX_ITERATION';

TRUNCATE TABLE SOM_MAP;
TRUNCATE TABLE SOM_RESULTS;

CALL _SYS_AFL.PAL_SOM (V_SOM_DATA, SOM_PARAMS, SOM_MAP, SOM_RESULTS) WITH OVERVIEW;

