-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_MODEL";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_ARIMA');
DROP TABLE "MODEL";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "PRICE" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_MODEL" AS TABLE ("NAME" VARCHAR(60), "VALUE" VARCHAR(5000));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_MODEL', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'AUTOARIMA', 'DEVUSER', 'P_ARIMA', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "MODEL" LIKE "T_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('SEARCH_STRATEGY', 0, null, null); -- 0: Exhaustive, 1: Stepwise
--INSERT INTO "#PARAMS" VALUES ('INFORMATION_CRITERION', 0, null, null); -- 0: AICC, 1: AIC, 2: BIC
--INSERT INTO "#PARAMS" VALUES ('CH_SIGNIFICANCE_LEVEL', null, 0.05, null); -- Default: 0.05
--INSERT INTO "#PARAMS" VALUES ('MAX_D', 2, null, null); -- Default: 2
--INSERT INTO "#PARAMS" VALUES ('D', -1, null, null); -- <0: Automatic, >=0: Use specified value
--INSERT INTO "#PARAMS" VALUES ('SEASONAL_D', -1, null, null); -- <0: Automatic, >=0: Use specified value
--INSERT INTO "#PARAMS" VALUES ('MAX_SEASONAL_D', 1, null, null); -- Default: 1
--INSERT INTO "#PARAMS" VALUES ('MAX_SEASONAL_P', 2, null, null); -- Default: 2
--INSERT INTO "#PARAMS" VALUES ('MAX_SEASONAL_Q', 2, null, null); -- Default: 2
--INSERT INTO "#PARAMS" VALUES ('INITIAL_P', 0, null, null); -- Default: 0 (Stepwise only)
--INSERT INTO "#PARAMS" VALUES ('INITIAL_Q', 0, null, null); -- Default: 0 (Stepwise only)
--INSERT INTO "#PARAMS" VALUES ('MAX_P', 5, null, null); -- Default: 5
--INSERT INTO "#PARAMS" VALUES ('MAX_Q', 5, null, null); -- Default: 5

TRUNCATE TABLE "MODEL";

CALL "P_ARIMA" ("PAL"."STOCKS", "#PARAMS", "MODEL") WITH OVERVIEW;

SELECT * FROM "MODEL";
