SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_SM_DATA;
DROP TYPE PAL_T_SM_PARAMS;
DROP TYPE PAL_T_SM_RESULTS;
DROP TABLE PAL_SM_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_SM');
DROP VIEW V_SM_DATA;
DROP TABLE SM_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_SM_DATA AS TABLE (LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);
CREATE TYPE PAL_T_SM_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_SM_RESULTS AS TABLE (ID VARCHAR(100), LIFESPEND DOUBLE, NEWSPEND DOUBLE, INCOME DOUBLE, LOYALTY DOUBLE);

CREATE COLUMN TABLE PAL_SM_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SM_SIGNATURE VALUES (1, 'PAL.PAL_T_SM_DATA', 'in');
INSERT INTO PAL_SM_SIGNATURE VALUES (2, 'PAL.PAL_T_SM_PARAMS', 'in');
INSERT INTO PAL_SM_SIGNATURE VALUES (3, 'PAL.PAL_T_SM_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_SM', 'AFLPAL', 'MULTIVARSTAT', PAL_SM_SIGNATURE);

-- app setup
CREATE VIEW V_SM_DATA AS 
	SELECT LIFESPEND, NEWSPEND, INCOME, LOYALTY 
		FROM CUSTOMERS
	;
CREATE COLUMN TABLE SM_RESULTS LIKE PAL_T_SM_RESULTS;

-- app runtime
DROP TABLE #SM_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #SM_PARAMS LIKE PAL_T_SM_PARAMS;
INSERT INTO #SM_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO #SM_PARAMS VALUES ('RESULT_TYPE', 1, null, null); -- 0: Covariance, 1: Pearson's			

TRUNCATE TABLE SM_RESULTS;

CALL _SYS_AFL.PAL_SM (V_SM_DATA, #SM_PARAMS, SM_RESULTS) WITH OVERVIEW;

SELECT * FROM V_SM_DATA;
SELECT * FROM SM_RESULTS;
