-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_RESULTS";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_LDACLASSIFY');
DROP VIEW "V_DATA";
DROP TABLE "RESULTS";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "ATTR1" DOUBLE, "ATTR2" DOUBLE, "ATTR3" DOUBLE, "ATTR4" DOUBLE);
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "CLASS" VARCHAR(50), "SCORE" DOUBLE);
CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PRIOR', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_CLASSIFIER', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_RESULTS', 'OUT');
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'LDACLASSIFY', 'DEVUSER', 'P_LDACLASSIFY', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS SELECT "ID", "ATTR1", "ATTR2", "ATTR3", "ATTR4" FROM "PAL"."CLASSIFICATION";
CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
--INSERT INTO "#PARAMS" VALUES ('VERBOSE_OUTPUT', 1, null, null); -- 0: no; 1: yes (default:0)

TRUNCATE TABLE "RESULTS";

CALL "P_LDACLASSIFY" ("V_DATA", "PRIOR", "CLASSIFIER", "#PARAMS", "RESULTS") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT a.*, b."CLASS" AS "RESULT_CLASS", b."SCORE"
 FROM "PAL"."CLASSIFICATION" a
 INNER JOIN "RESULTS" b ON (a."ID"=b."ID")
 ;
