SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_TS_DATA;
DROP TYPE PAL_T_TS_PARAMS;
DROP TYPE PAL_T_TS_OPTIMAL_PARAMS;
DROP TYPE PAL_T_TS_RESULTS;
DROP TABLE PAL_TS_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_TS');
DROP TABLE TS_OPTIMAL_PARAMS;
DROP TABLE TS_RESULTS;
DROP VIEW V_TS_DATA;
DROP VIEW V_TS_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_TS_DATA AS TABLE (CALENDAR_ID INTEGER, SALES_AMOUNT DOUBLE);
CREATE TYPE PAL_T_TS_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_TS_OPTIMAL_PARAMS AS TABLE (NAME VARCHAR(100), VALUE DOUBLE);
--CREATE TYPE PAL_T_TS_OPTIMAL_PARAMS AS TABLE (NAME VARCHAR(100), VALUE VARCHAR(5000));
CREATE TYPE PAL_T_TS_RESULTS AS TABLE (CALENDAR_ID INTEGER, SALES_AMOUNT DOUBLE, ERROR DOUBLE);

CREATE COLUMN TABLE PAL_TS_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_TS_SIGNATURE VALUES (1, 'PAL.PAL_T_TS_DATA', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (2, 'PAL.PAL_T_TS_PARAMS', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (3, 'PAL.PAL_T_TS_OPTIMAL_PARAMS', 'out');
INSERT INTO PAL_TS_SIGNATURE VALUES (4, 'PAL.PAL_T_TS_RESULTS', 'out');

GRANT SELECT ON PAL_TS_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_TS', 'AFLPAL', 'FORECASTSMOOTHING', PAL_TS_SIGNATURE);

-- app setup
CREATE VIEW V_TS_DATA AS 
	SELECT CALENDAR_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT 
		FROM ORDER_FACTS
		WHERE ITEM_ID BETWEEN 30 AND 39
		GROUP BY CALENDAR_ID 
		ORDER BY CALENDAR_ID
	;
CREATE COLUMN TABLE TS_OPTIMAL_PARAMS LIKE PAL_T_TS_OPTIMAL_PARAMS;
CREATE COLUMN TABLE TS_RESULTS LIKE PAL_T_TS_RESULTS;
CREATE VIEW V_TS_RESULTS AS
	SELECT 
		CASE WHEN a.CALENDAR_ID IS NOT NULL THEN a.CALENDAR_ID ELSE b.CALENDAR_ID END AS CALENDAR_ID, 
		a.SALES_AMOUNT, 
		ROUND(b.SALES_AMOUNT) AS SALES_AMOUNT_PREDICTED 
	 FROM V_TS_DATA a 
	 FULL JOIN TS_RESULTS b ON (a.CALENDAR_ID=b.CALENDAR_ID) 
	;

-- app runtime
DROP TABLE #TS_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #TS_PARAMS LIKE PAL_T_TS_PARAMS;
INSERT INTO #TS_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #TS_PARAMS VALUES ('FORECAST_MODEL_NAME', null, null, 'SESM'); SESM: Single, DESM: Double, TESM: Triple
INSERT INTO #TS_PARAMS VALUES ('FORECAST_NUM', 6, null, null);
INSERT INTO #TS_PARAMS VALUES ('STARTTIME', 0, null, null);
INSERT INTO #TS_PARAMS VALUES ('CYCLE', 3, null, null);
--INSERT INTO #TS_PARAMS VALUES ('FORECAST_AUTOMATIC', 0, null, null);
--INSERT INTO #TS_PARAMS VALUES ('ALPHA', null, 0.1, null); 0-1 for smoothing weight
--INSERT INTO #TS_PARAMS VALUES ('BETA', null, 0.1, null); 0-1 for trend (DESM & TESM)
--INSERT INTO #TS_PARAMS VALUES ('GAMMA', null, 0.1, null); 0-1 for seasonality (TESM)
-- NEW WITH SPS08
--INSERT INTO #TS_PARAMS VALUES ('MODELSELECTION', 1, null, null);
--INSERT INTO #TS_PARAMS VALUES ('OPTIMIZER_TIME_BUDGET', 10, null, null);
--INSERT INTO #TS_PARAMS VALUES ('OPTIMIZER_RANDOM_SEED', 123, null, null); -- default is system time

TRUNCATE TABLE TS_OPTIMAL_PARAMS;
TRUNCATE TABLE TS_RESULTS;

CALL _SYS_AFL.PAL_TS (V_TS_DATA, #TS_PARAMS, TS_OPTIMAL_PARAMS, TS_RESULTS) WITH OVERVIEW;

SELECT * FROM V_TS_DATA;
SELECT * FROM TS_OPTIMAL_PARAMS;
SELECT * FROM TS_RESULTS;
SELECT * FROM V_TS_RESULTS;
