-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_DICT";
DROP TYPE "T_TOPICWORD";
DROP TYPE "T_DOCTOPIC";
DROP TYPE "T_GENERALINFO";
DROP TYPE "T_TOPICTOPWORDS";
DROP TYPE "T_WORDTOPICASSIGNMENT";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_LDA');
DROP TABLE "DATA";
DROP TABLE "DICT";
DROP TABLE "TOPICWORD";
DROP TABLE "DOCTOPIC";
DROP TABLE "GENERALINFO";
DROP TABLE "TOPICTOPWORDS";
DROP TABLE "WORDTOPICASSIGNMENT";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("DOCID" INTEGER, "TEXT" VARCHAR(1000));
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_DICT" AS TABLE ("WORDID" INTEGER, "WORD" VARCHAR(1000));
CREATE TYPE "T_TOPICWORD" AS TABLE ("TOPICID" INTEGER, "WORDID" INTEGER, "PROBABILITY" DOUBLE);
CREATE TYPE "T_DOCTOPIC" AS TABLE ("DOCID" INTEGER, "TOPICID" INTEGER, "PROBABILITY" DOUBLE);
CREATE TYPE "T_GENERALINFO" AS TABLE ("NAME" VARCHAR(60), "INTVAL" INTEGER, "DOUBLEVAL" DOUBLE, "STRINGVAL" VARCHAR(100));
CREATE TYPE "T_TOPICTOPWORDS" AS TABLE ("TOPICID" INTEGER, "WORDS" VARCHAR(1000));
CREATE TYPE "T_WORDTOPICASSIGNMENT" AS TABLE ("DOCID" INTEGER, "WORDID" INTEGER, "TOPICID" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_DICT', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_TOPICWORD', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_DOCTOPIC', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_GENERALINFO', 'OUT');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_TOPICTOPWORDS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (8, 'DEVUSER', 'T_WORDTOPICASSIGNMENT', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'LDAESTIMATE', 'DEVUSER', 'P_LDA', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "DATA" LIKE "T_DATA";
INSERT INTO "DATA" VALUES (1, 'I eat fish and vegetables');
INSERT INTO "DATA" VALUES (2, 'Fish are pets');
INSERT INTO "DATA" VALUES (3, 'My kitten eats fish');

CREATE COLUMN TABLE "DICT" LIKE "T_DICT";
CREATE COLUMN TABLE "TOPICWORD" LIKE "T_TOPICWORD";
CREATE COLUMN TABLE "DOCTOPIC" LIKE "T_DOCTOPIC";
CREATE COLUMN TABLE "GENERALINFO" LIKE "T_GENERALINFO";
CREATE COLUMN TABLE "TOPICTOPWORDS" LIKE "T_TOPICTOPWORDS";
CREATE COLUMN TABLE "WORDTOPICASSIGNMENT" LIKE "T_WORDTOPICASSIGNMENT";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('TOPICS', 2, null, null);
INSERT INTO "#PARAMS" VALUES ('INIT', 0, null, null);
INSERT INTO "#PARAMS" VALUES ('BURNIN', 0, null, null);
INSERT INTO "#PARAMS" VALUES ('THIN', 1, null, null);
INSERT INTO "#PARAMS" VALUES ('ITERATION', 100, null, null);
INSERT INTO "#PARAMS" VALUES ('SEED', 0, null, null);
INSERT INTO "#PARAMS" VALUES ('ALPHA', null, 0.1, null);
INSERT INTO "#PARAMS" VALUES ('BETA', null, 0.1, null);
INSERT INTO "#PARAMS" VALUES ('MAX_TOP_WORDS', 3, null, null);
INSERT INTO "#PARAMS" VALUES ('DELIMIT', null, null, ' ');

TRUNCATE TABLE "DICT";
TRUNCATE TABLE "TOPICWORD";
TRUNCATE TABLE "DOCTOPIC";
TRUNCATE TABLE "GENERALINFO";
TRUNCATE TABLE "TOPICTOPWORDS";
TRUNCATE TABLE "WORDTOPICASSIGNMENT";

CALL "P_LDA" ("DATA", "#PARAMS", "DICT", "TOPICWORD", "DOCTOPIC", "GENERALINFO", "TOPICTOPWORDS", "WORDTOPICASSIGNMENT") WITH OVERVIEW;

SELECT * FROM "DICT";
SELECT * FROM "TOPICWORD";
SELECT * FROM "DOCTOPIC";
SELECT * FROM "GENERALINFO";
SELECT * FROM "TOPICTOPWORDS";
SELECT * FROM "WORDTOPICASSIGNMENT";
