SET SCHEMA PAL;

-- cleanup
DROP TYPE PAL_T_DQ_DATA;
DROP TYPE PAL_T_DQ_DIST;
DROP TYPE PAL_T_DQ_PARAMS;
DROP TYPE PAL_T_DQ_RESULTS;
DROP TABLE PAL_DQ_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_DQ');
DROP TABLE DQ_DATA;
DROP TABLE DQ_RESULTS;

-- PAL setup
CREATE TYPE PAL_T_DQ_DATA AS TABLE (PROBABILITY DOUBLE);
CREATE TYPE PAL_T_DQ_DIST AS TABLE (NAME VARCHAR(60), VALUE VARCHAR(60));
CREATE TYPE PAL_T_DQ_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_DQ_RESULTS AS TABLE (PROBABILITY DOUBLE, VALUE DOUBLE);

CREATE COLUMN TABLE PAL_DQ_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_DQ_SIGNATURE VALUES (1, 'PAL.PAL_T_DQ_DATA', 'in');
INSERT INTO PAL_DQ_SIGNATURE VALUES (2, 'PAL.PAL_T_DQ_DIST', 'in');
INSERT INTO PAL_DQ_SIGNATURE VALUES (3, 'PAL.PAL_T_DQ_PARAMS', 'in');
INSERT INTO PAL_DQ_SIGNATURE VALUES (4, 'PAL.PAL_T_DQ_RESULTS', 'out');

GRANT SELECT ON PAL_DQ_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_DQ', 'AFLPAL', 'DISTRQUANTILE', PAL_DQ_SIGNATURE);

-- app setup
CREATE TABLE DQ_DATA LIKE PAL_T_DQ_DATA;
INSERT INTO DQ_DATA VALUES (0.05);
INSERT INTO DQ_DATA VALUES (0.10);
INSERT INTO DQ_DATA VALUES (0.15);
INSERT INTO DQ_DATA VALUES (0.20);
INSERT INTO DQ_DATA VALUES (0.25);
INSERT INTO DQ_DATA VALUES (0.30);
INSERT INTO DQ_DATA VALUES (0.35);
INSERT INTO DQ_DATA VALUES (0.40);
INSERT INTO DQ_DATA VALUES (0.45);
INSERT INTO DQ_DATA VALUES (0.50);
INSERT INTO DQ_DATA VALUES (0.55);
INSERT INTO DQ_DATA VALUES (0.60);
INSERT INTO DQ_DATA VALUES (0.65);
INSERT INTO DQ_DATA VALUES (0.70);
INSERT INTO DQ_DATA VALUES (0.75);
INSERT INTO DQ_DATA VALUES (0.80);
INSERT INTO DQ_DATA VALUES (0.85);
INSERT INTO DQ_DATA VALUES (0.90);
INSERT INTO DQ_DATA VALUES (0.95);
CREATE COLUMN TABLE DQ_RESULTS LIKE PAL_T_DQ_RESULTS;

-- app runtime
DROP TABLE #DQ_DIST;
CREATE LOCAL TEMPORARY COLUMN TABLE #DQ_DIST LIKE PAL_T_DQ_DIST;
INSERT INTO #DQ_DIST VALUES ('DISTRIBUTIONNAME', 'WEIBULL'); -- uniform, normal, weibull, gamma
INSERT INTO #DQ_DIST VALUES ('MIN', '0'); -- uniform
INSERT INTO #DQ_DIST VALUES ('MAX', '1'); -- uniform
INSERT INTO #DQ_DIST VALUES ('MEAN', '0'); -- normal
INSERT INTO #DQ_DIST VALUES ('VARIANCE', '1'); -- normal
INSERT INTO #DQ_DIST VALUES ('SHAPE', '2.06698'); -- weibull, gamma
INSERT INTO #DQ_DIST VALUES ('SCALE', '244.401'); -- weibull, gamma

DROP TABLE #DQ_PARAMS;
CREATE LOCAL TEMPORARY COLUMN TABLE #DQ_PARAMS LIKE PAL_T_DQ_PARAMS;
INSERT INTO #DQ_PARAMS VALUES ('LOWER_UPPER', 0, null, null); -- 0: CDF, 1: CCDF

TRUNCATE TABLE DQ_RESULTS;

CALL _SYS_AFL.PAL_DQ (DQ_DATA, #DQ_DIST, #DQ_PARAMS, DQ_RESULTS) WITH OVERVIEW;

SELECT * FROM DQ_RESULTS;
