SET SCHEMA PAL;

-- PAL setup

CREATE TYPE PAL_T_TS_DATA AS TABLE (CALENDAR_ID INT, SALES_AMOUNT DOUBLE);
CREATE TYPE PAL_T_TS_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE PAL_T_TS_RESULTS AS TABLE (CALENDAR_ID INT, SALES_AMOUNT DOUBLE);

CREATE COLUMN TABLE PAL_TS_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_TS_SIGNATURE VALUES (1, 'PAL.PAL_T_TS_DATA', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (2, 'PAL.PAL_T_TS_PARAMS', 'in');
INSERT INTO PAL_TS_SIGNATURE VALUES (3, 'PAL.PAL_T_TS_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('PAL_TS_S', 'AFLPAL', 'SINGLESMOOTH', PAL_TS_SIGNATURE);


-- the afl_wrapper_eraser effectively performs the following:
/*
DROP PROCEDURE _SYS_AFL.PAL_TS_S;
DROP TYPE _SYS_AFL.PAL_TS_S__TT_P1;
DROP TYPE _SYS_AFL.PAL_TS_S__TT_P2;
DROP TYPE _SYS_AFL.PAL_TS_S__TT_P3;
*/

CALL SYSTEM.AFL_WRAPPER_ERASER ('PAL_TS_S');

-- for usage by none SYSTEM user
GRANT EXECUTE ON SYSTEM.AFL_WRAPPER_ERASER TO PAL_DEV;
