-- cleanup
DROP TYPE "T_FUNCTION";
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_RESULTS";
DROP TYPE "T_SELECTED_PARAMS";
DROP TYPE "T_MODEL1";
DROP TYPE "T_MODEL2";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_PSME');
DROP TABLE "FUNCTION";
DROP TABLE "RESULTS";
DROP TABLE "SELECTED_PARAMS";
DROP TABLE "MODEL1";
DROP TABLE "MODEL2";

-- procedure setup
CREATE TYPE "T_FUNCTION" AS TABLE ("ID" INTEGER, "NAME" VARCHAR(60));
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "FRAUD" INTEGER, "POLICY" INTEGER, "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" INTEGER);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR (100));
CREATE TYPE "T_RESULTS" AS TABLE ("ID" INTEGER, "NAME" VARCHAR(60), "VALUE" VARCHAR(5000));
CREATE TYPE "T_SELECTED_PARAMS" AS TABLE ("ID" INTEGER, "NAME" VARCHAR(60), "VALUE" VARCHAR(60));
CREATE TYPE "T_MODEL1" AS TABLE ("NAME" VARCHAR(50), "VALUE" DOUBLE);
CREATE TYPE "T_MODEL2" AS TABLE ("ID" INTEGER, "ALPHA" DOUBLE, "POLICY" INTEGER, "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" INTEGER);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_FUNCTION', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_RESULTS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_SELECTED_PARAMS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_MODEL1', 'OUT');
INSERT INTO "SIGNATURE" VALUES (7, 'DEVUSER', 'T_MODEL2', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'PSME', 'DEVUSER', 'P_PSME', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "FUNCTION" LIKE "T_FUNCTION";
INSERT INTO "FUNCTION" VALUES (1, 'SVMTRAIN'); -- LOGISTICREGRESSION, NBCTRAIN, SVMTRAIN

CREATE COLUMN TABLE "RESULTS" LIKE "T_RESULTS";
CREATE COLUMN TABLE "SELECTED_PARAMS" LIKE "T_SELECTED_PARAMS";
CREATE COLUMN TABLE "MODEL1" LIKE "T_MODEL1";
CREATE COLUMN TABLE "MODEL2" LIKE "T_MODEL2";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('PARAM_SELECTION', 1, null, null); -- 0: Disabled; 1: Enabled
INSERT INTO "#PARAMS" VALUES ('PARAM_SELECTION_MEASURE', null, null, 'ACCURACY'); -- ACCURACY, F1_SCORE
INSERT INTO "#PARAMS" VALUES ('NR_FOLD', 3, null, null); -- # Portions in x-validation
INSERT INTO "#PARAMS" VALUES ('EVALUATION_SEED', 0, null, null); -- 0: System time; >0 Use specified seed
-- SVM specific
INSERT INTO "#PARAMS" VALUES ('TYPE', 1, null, null); -- 1: Classification; 2: Regression; 3: Ranking

TRUNCATE TABLE "RESULTS";
TRUNCATE TABLE "SELECTED_PARAMS";
TRUNCATE TABLE "MODEL1";
TRUNCATE TABLE "MODEL2";

CALL "P_PSME" ("FUNCTION", "PAL"."FRAUD", "#PARAMS", "RESULTS", "SELECTED_PARAMS", "MODEL1", "MODEL2") WITH OVERVIEW;

SELECT * FROM "RESULTS";
SELECT * FROM "SELECTED_PARAMS";
SELECT * FROM "MODEL1";
SELECT * FROM "MODEL2";
