-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_MODEL";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_ARIMA');
DROP TABLE "MODEL";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "PRICE" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_MODEL" AS TABLE ("NAME" VARCHAR(60), "VALUE" VARCHAR(5000));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_MODEL', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'ARIMATRAIN', 'DEVUSER', 'P_ARIMA', "SIGNATURE");

-- data setup
CREATE COLUMN TABLE "MODEL" LIKE "T_MODEL";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO "#PARAMS" VALUES ('METHOD', 1, null, null); -- 0: conditional sum squares, 1: max likelihood estimation
--INSERT INTO "#PARAMS" VALUES ('STATIONARY', 1, null, null); -- 0: result may not be stationary, 1: is stationary
--INSERT INTO "#PARAMS" VALUES ('P', 1, null, null); -- Auto Regression
--INSERT INTO "#PARAMS" VALUES ('D', 0, null, null); -- Differentiation
--INSERT INTO "#PARAMS" VALUES ('Q', 1, null, null); -- Moving Average
INSERT INTO "#PARAMS" VALUES ('SEASONAL_P', 1, null, null); -- Seasonal Auto Regression
INSERT INTO "#PARAMS" VALUES ('SEASONAL_D', 1, null, null); -- Seasonal Differentiation
INSERT INTO "#PARAMS" VALUES ('SEASONAL_Q', 1, null, null); -- Seasonal Moving Average
INSERT INTO "#PARAMS" VALUES ('SEASONAL_PERIOD', 6, null, null); -- Seasonal Period

TRUNCATE TABLE "MODEL";

CALL "P_ARIMA" ("PAL"."STOCKS", "#PARAMS", "MODEL") WITH OVERVIEW;

SELECT * FROM "MODEL";
