-- cleanup
DROP TYPE "T_FAM_DATA";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_FAM');
DROP TABLE "SIGNATURE";
DROP VIEW "V_FAM_DATA";
DROP TABLE "FAM_STATS";

-- procedure setup
CREATE TYPE "T_FAM_DATA" AS TABLE ("SALES_AMOUNT" DOUBLE, "SALES_AMOUNT_PREDICTED" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_FAM_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_STATS', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'ACCURACYMEASURES', 'DEVUSER', 'P_FAM', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_FAM_DATA" AS 
	SELECT 
		a."SALES_AMOUNT", 
		ROUND(b."SALES_AMOUNT") AS "SALES_AMOUNT_PREDICTED"
	 FROM "V_DATA" a 
	 INNER JOIN "RESULTS" b ON (a."CALENDAR_ID"=b."CALENDAR_ID") 
	 ;
CREATE COLUMN TABLE "FAM_STATS" LIKE "T_STATS";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MPE'); 
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MSE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'RMSE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'ET');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MAD'); 
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MASE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'WMAPE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'SMAPE');
INSERT INTO "#PARAMS" VALUES ('MEASURE_NAME', null, null, 'MAPE');

TRUNCATE TABLE "FAM_STATS";

CALL "P_FAM" ("V_FAM_DATA", "#PARAMS", "FAM_STATS") WITH OVERVIEW;

SELECT * FROM "V_FAM_DATA";
SELECT * FROM "FAM_STATS";
