-- cleanup
DROP TYPE "T_DATA";
DROP TYPE "T_PARAMS";
DROP TYPE "T_STATS";
DROP TYPE "T_MAUCHLY";
DROP TYPE "T_ANOVA";
DROP TYPE "T_MULTICOMPARISON";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_ANOVARM');
DROP VIEW "V_DATA";
DROP TABLE "STATS";
DROP TABLE "MAUCHLY";
DROP TABLE "ANOVA";
DROP TABLE "MULTICOMPARISON";

-- procedure setup
CREATE TYPE "T_DATA" AS TABLE ("ID" INTEGER, "LIFESPEND" DOUBLE, "NEWSPEND" DOUBLE, "INCOME" DOUBLE, "LOYALTY" DOUBLE);
CREATE TYPE "T_PARAMS" AS TABLE ("NAME" VARCHAR(60), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "T_STATS" AS TABLE ("GROUP" VARCHAR(60), "SAMPLES" INTEGER, "MEAN" DOUBLE, "STDDEV" DOUBLE);
CREATE TYPE "T_MAUCHLY" AS TABLE ("NAME" VARCHAR(60), "VALUE" DOUBLE);
CREATE TYPE "T_ANOVA" AS TABLE ("SOURCE" VARCHAR(60), "SUMSQUARES" DOUBLE, "DEGREESFREEDOM" DOUBLE, "MEANSQUARES" DOUBLE, "FRATIO" DOUBLE, "PVALUE" DOUBLE, "PVALUE_GREENHOUSE_GEISSER" DOUBLE, "PVALUE_HUYNH_FELDT" DOUBLE, "PVALUE_LOWER_CORRECTION" DOUBLE);
CREATE TYPE "T_MULTICOMPARISON" AS TABLE ("FIRST_GROUP" VARCHAR(60), "SECOND_GROUP" VARCHAR(60), "MEANDIFF" DOUBLE, "STDERR" DOUBLE, "PVALUE" DOUBLE, "CL_LOWER" DOUBLE, "CL_UPPER" DOUBLE);

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_STATS', 'OUT');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_MAUCHLY', 'OUT');
INSERT INTO "SIGNATURE" VALUES (5, 'DEVUSER', 'T_ANOVA', 'OUT');
INSERT INTO "SIGNATURE" VALUES (6, 'DEVUSER', 'T_MULTICOMPARISON', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'ANOVAONEWAYRM', 'DEVUSER', 'P_ANOVARM', "SIGNATURE");

-- data & view setup
CREATE VIEW "V_DATA" AS 
	SELECT "ID", "LIFESPEND", "NEWSPEND", "INCOME", "LOYALTY"
		FROM "PAL"."CUSTOMERS"
	;
CREATE TABLE "STATS" LIKE "T_STATS";
CREATE TABLE "MAUCHLY" LIKE "T_MAUCHLY";
CREATE TABLE "ANOVA" LIKE "T_ANOVA";
CREATE TABLE "MULTICOMPARISON" LIKE "T_MULTICOMPARISON";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";
INSERT INTO "#PARAMS" VALUES ('MULTCOMP_METHOD', 0, null, null); -- 0: Tukey-Kramer, 1: Bonferroni, 2: Dunn-Sidak, 3: Scheffe, 4: Fisher’s LSD (default:0)
INSERT INTO "#PARAMS" VALUES ('SIGNIFICANCE_LEVEL', null, 0.05, null); -- default 0.05 (0 < 1)
INSERT INTO "#PARAMS" VALUES ('SE_TYPE', 1, null, null); -- 0: all data, 1: groups compared (default:1)

TRUNCATE TABLE "STATS";
TRUNCATE TABLE "MAUCHLY";
TRUNCATE TABLE "ANOVA";
TRUNCATE TABLE "MULTICOMPARISON";

CALL "P_ANOVARM" ("V_DATA", "#PARAMS", "STATS", "MAUCHLY", "ANOVA", "MULTICOMPARISON") WITH OVERVIEW;

SELECT * FROM "STATS";
SELECT * FROM "MAUCHLY";
SELECT * FROM "ANOVA";
SELECT * FROM "MULTICOMPARISON";

