-- cleanup
DROP TYPE "T_DATA_P";
DROP TYPE "T_PREDICT";
DROP TABLE "SIGNATURE";
CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_DROP"('DEVUSER', 'P_BPNN_P');
DROP TABLE "DATA_P";
DROP TABLE "PREDICT";

-- procedure setup
CREATE TYPE "T_DATA_P" AS TABLE ("ID" INT, "POLICY" VARCHAR(10), "AGE" INTEGER, "AMOUNT" INTEGER, "OCCUPATION" VARCHAR(10));
CREATE TYPE "T_PREDICT" AS TABLE ("ID" INT, "FRAUD" VARCHAR(10));

CREATE COLUMN TABLE "SIGNATURE" ("POSITION" INTEGER, "SCHEMA_NAME" VARCHAR(100), "TYPE_NAME" VARCHAR(100), "PARAMETER_TYPE" VARCHAR(100));
INSERT INTO "SIGNATURE" VALUES (1, 'DEVUSER', 'T_DATA_P', 'IN');
INSERT INTO "SIGNATURE" VALUES (2, 'DEVUSER', 'T_MODEL', 'IN');
INSERT INTO "SIGNATURE" VALUES (3, 'DEVUSER', 'T_PARAMS', 'IN');
INSERT INTO "SIGNATURE" VALUES (4, 'DEVUSER', 'T_PREDICT', 'OUT');

CALL "SYS"."AFLLANG_WRAPPER_PROCEDURE_CREATE"('AFLPAL', 'PREDICTWITHBPNN', 'DEVUSER', 'P_BPNN_P', "SIGNATURE");

-- data & view setup
CREATE COLUMN TABLE "DATA_P" LIKE "T_DATA_P";
INSERT INTO "DATA_P" VALUES (1, 'Travel', 56, 350, 'IT');
INSERT INTO "DATA_P" VALUES (2, 'Vehicle', 26, 6230, 'Marketing');
INSERT INTO "DATA_P" VALUES (3, 'Home', 55, 2300, 'Marketing');
INSERT INTO "DATA_P" VALUES (4, 'Vehicle', 31, 2134, 'Marketing');
INSERT INTO "DATA_P" VALUES (5, 'Home', 37, 2900, 'Sales');

CREATE COLUMN TABLE "PREDICT" LIKE "T_PREDICT";

-- runtime
DROP TABLE "#PARAMS";
CREATE LOCAL TEMPORARY COLUMN TABLE "#PARAMS" LIKE "T_PARAMS";

TRUNCATE TABLE "PREDICT";

CALL "P_BPNN_P" ("DATA_P", "MODEL", "#PARAMS", "PREDICT") WITH OVERVIEW;

SELECT * FROM "PREDICT";

SELECT d.*, p."FRAUD" 
 FROM "DATA_P" d
 INNER JOIN "PREDICT" p ON (p."ID"=d."ID")
 ;
