DROP SCHEMA PAL CASCADE;

CREATE SCHEMA PAL;

SET SCHEMA PAL;

CREATE COLUMN TABLE "CUSTOMERS" (
	 "ID" INTEGER NOT NULL,
	 "CUSTOMER" NVARCHAR(60),
	 "LIFESPEND" DOUBLE,
	 "NEWSPEND" DOUBLE,
	 "INCOME" DOUBLE,
	 "LOYALTY" DOUBLE,
	 PRIMARY KEY ("ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMERS_INCOME" (
	 "ID" INTEGER NOT NULL,
	 "INCOME" INTEGER,
	 PRIMARY KEY ("ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMERS_AD" 
	 LIKE "CUSTOMERS" WITH NO DATA
	 ;

CREATE COLUMN TABLE "CUSTOMERS_RG" 
	 LIKE "CUSTOMERS" WITH NO DATA
	 ;

CREATE COLUMN TABLE "CUSTOMERS1M" 
	 LIKE "CUSTOMERS" WITH NO DATA
	 ;

CREATE COLUMN TABLE "CALENDAR" (
	 "CALENDAR_ID" INTEGER NOT NULL,
	 "CALENDAR_YEAR" SMALLINT,
	 "CALENDAR_MONTH" SMALLINT,
	 "CALENDAR_YYYYMM" NVARCHAR(7),
	 PRIMARY KEY ("CALENDAR_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER" (
	 "CUSTOMER_ID" INTEGER NOT NULL,
	 "CUSTOMER_CHILDREN" SMALLINT,
	 "CUSTOMER_GENDER_ID" SMALLINT,
	 "CUSTOMER_MARITAL_STATUS_ID" SMALLINT,
	 "CUSTOMER_MORTGAGE_ID" SMALLINT,
	 "CUSTOMER_AGE_ID" SMALLINT,
	 "CUSTOMER_INCOME_ID" SMALLINT,
	 "CUSTOMER_NAME" NVARCHAR(60),
	 "CUSTOMER_JOB" NVARCHAR(60),
	 "CUSTOMER_EDUCATION" NVARCHAR(60),
	 "CUSTOMER_EMAIL" NVARCHAR(60),
	 "CUSTOMER_CITY" NVARCHAR(60),
	 "CUSTOMER_TIMESTAMP" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER_AGE" (
	 "CUSTOMER_AGE_ID" SMALLINT,
	 "CUSTOMER_AGE_NAME" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_AGE_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER_GENDER" (
	 "CUSTOMER_GENDER_ID" SMALLINT,
	 "CUSTOMER_GENDER_NAME" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_GENDER_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER_INCOME" (
	 "CUSTOMER_INCOME_ID" SMALLINT,
	 "CUSTOMER_INCOME_NAME" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_INCOME_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER_MARITAL_STATUS" (
	 "CUSTOMER_MARITAL_STATUS_ID" SMALLINT,
	 "CUSTOMER_MARITAL_STATUS_NAME" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_MARITAL_STATUS_ID"))
	 ;

CREATE COLUMN TABLE "CUSTOMER_MORTGAGE" (
	 "CUSTOMER_MORTGAGE_ID" SMALLINT,
	 "CUSTOMER_MORTGAGE_NAME" NVARCHAR(60),
	 PRIMARY KEY ("CUSTOMER_MORTGAGE_ID"))
	 ;

CREATE COLUMN TABLE "ITEM" (
	 "ITEM_ID" INTEGER NOT NULL,
	 "ITEM_NAME" NVARCHAR(60),
	 "ITEM_GROUP" NVARCHAR(60),
	 PRIMARY KEY ("ITEM_ID"))
	 ;

CREATE COLUMN TABLE "ORDER_FACTS" (
 	"ORDER_ID" INTEGER NOT NULL,
	"CALENDAR_ID" INTEGER,
	"CUSTOMER_ID" INTEGER,
	"ITEM_ID" INTEGER,
	"ITEMS_SOLD" SMALLINT,
	"SALES_AMOUNT" INTEGER,
	PRIMARY KEY ("ORDER_ID"))
	;

CREATE COLUMN TABLE "FCTCUSTOMERORDER" (
	 "ORDERID" INTEGER CS_INT NOT NULL ,
	 "PRODUCTID" INTEGER CS_INT NOT NULL ,
	 "CUSTOMERID" INTEGER CS_INT NOT NULL ,
	 "EMPLOYEEID" INTEGER CS_INT,
	 "PROMOTIONID" INTEGER CS_INT,
	 "TERRITORYID" INTEGER CS_INT,
	 "ORDERPERIODID" INTEGER CS_INT,
	 "REQUIREDPERIODID" INTEGER CS_INT,
	 "SHIPPEDPERIODID" INTEGER CS_INT,
	 "SHIPPERID" INTEGER CS_INT,
	 "UNITPRICE" DECIMAL(19,4) CS_FIXED,
	 "QUANTITY" INTEGER CS_INT,
	 "DISCOUNT" DECIMAL(19,10) CS_FIXED,
	 "UNITSALES" DECIMAL(19,2) CS_FIXED,
	 "NETSALES" DECIMAL(19,2) CS_FIXED,
	 "UNITCOST" DECIMAL(19,4) CS_FIXED,
	 "FREIGHT" DOUBLE CS_DOUBLE,
	 "COST" DECIMAL(19,4) CS_FIXED,
	 "QUANTITYORDERED" INTEGER CS_INT,
	 "DELIVEREDPERIODID" INTEGER CS_INT,
	 PRIMARY KEY ("ORDERID", "PRODUCTID", "CUSTOMERID"))
	 ;

CREATE COLUMN TABLE "CLAIMS" (
	 "ID" INTEGER NOT NULL,
	 "POLICY" NVARCHAR(10),
	 "AGE" INTEGER,
	 "AMOUNT" INTEGER,
	 "OCCUPATION" NVARCHAR(10),
	 "FRAUD" NVARCHAR(10),
	 PRIMARY KEY ("ID"))
	 ;

CREATE COLUMN TABLE "CLAIMS_MV" (
	 "ID" INTEGER NOT NULL,
	 "POLICY" NVARCHAR(10),
	 "AGE" INTEGER,
	 "AMOUNT" INTEGER,
	 "OCCUPATION" NVARCHAR(10),
	 "FRAUD" NVARCHAR(10),
	 PRIMARY KEY ("ID"))
	 ;

CREATE COLUMN TABLE "FRAUD" (
	 "ID" INTEGER NOT NULL,
	 "FRAUD" INTEGER,
	 "POLICY" INTEGER,
	 "AGE" INTEGER,
	 "AMOUNT" INTEGER,
	 "OCCUPATION" INTEGER,
	 PRIMARY KEY ("ID"))
	 ;
 
CREATE COLUMN TABLE "STOCKS" (
	 "ID" INTEGER NOT NULL,
	 "PRICE" DOUBLE,
	 PRIMARY KEY ("ID"))
	 ;

CREATE COLUMN TABLE "FAILURES" (
	 "VALUE" DOUBLE
	 )
	 ;

CREATE COLUMN TABLE "FAILURES_CENSORED" (
	 "VALUE_LEFT" DOUBLE,
	 "VALUE_RIGHT" DOUBLE
	 )
	 ;
