SET SCHEMA PAL;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMERS.csv' 
	   INTO "CUSTOMERS" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMERS.err' TABLE LOCK
       ;

INSERT INTO CUSTOMERS_INCOME (ID, INCOME) 
	SELECT ID, CAST(INCOME * 20000 AS INTEGER) AS INCOME 
	 FROM CUSTOMERS
	;

INSERT INTO CUSTOMERS_AD SELECT * FROM CUSTOMERS;
INSERT INTO CUSTOMERS_AD VALUES (151, 'Anomaly I Am', 1, 2, 2.5, 0.75);

INSERT INTO CUSTOMERS_RG VALUES (1, 'Customer 1', 19, 2, 1, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (2, 'Customer 2', 17, 3, 2, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (3, 'Customer 3', 9, 4, 3, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (4, 'Customer 4', 12, 5, 4, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (5, 'Customer 5', 8, 6, 5, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (6, 'Customer 6', 6, 5, 6, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (7, 'Customer 7', 3, 4, 7, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (8, 'Customer 8', 4, 3, 8, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (9, 'Customer 9', 3.5, 2, 9, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (10, 'Customer 10', 7.5, 1, 10, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (11, 'Customer 11', 4.5, 2, 11, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (12, 'Customer 12', 13, 3, 12, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (13, 'Customer 13', 11.5, 4, 13, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (14, 'Customer 14', 16, 5, 14, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (15, 'Customer 15', 16.5, 6, 15, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (16, 'Customer 16', 18, 7, 16, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (17, 'Customer 17', 17.5, 6, 17, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (18, 'Customer 18', 10, 5, 18, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (19, 'Customer 19', 14, 4, 19, 0.75);
INSERT INTO CUSTOMERS_RG VALUES (20, 'Customer 20', 7, 3, 20, 0.75);

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMERS1M.csv' 
	   INTO "CUSTOMERS1M" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMERS1M.err' THREADS 10 BATCH 10000 TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CALENDAR.csv' 
	   INTO "CALENDAR"
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CALENDAR.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER.csv' 
	   INTO "CUSTOMER" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER.err' THREADS 10 BATCH 10000 TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER_AGE.csv' 
	   INTO "CUSTOMER_AGE" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER_AGE.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER_GENDER.csv' 
	   INTO "CUSTOMER_GENDER" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER_GENDER.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER_INCOME.csv' 
	   INTO "CUSTOMER_INCOME" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER_INCOME.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER_MARITAL_STATUS.csv' 
	   INTO "CUSTOMER_MARITAL_STATUS" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER_MARITAL_STATUS.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/CUSTOMER_MORTGAGE.csv' 
	   INTO "CUSTOMER_MORTGAGE" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'CUSTOMER_MORTGAGE.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/ITEM.csv' 
	   INTO "ITEM" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'ITEM.err' TABLE LOCK
       ;

IMPORT FROM CSV FILE '/tmp/PAL/ORDER_FACTS.csv' 
	   INTO "ORDER_FACTS" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'ORDER_FACTS.err' THREADS 10 BATCH 10000 TABLE LOCK
       ;

IMPORT FROM '/tmp/PAL/FCTCUSTOMERORDER.ctl';
UPDATE FCTCUSTOMERORDER MERGE DELTA INDEX;

INSERT INTO "CLAIMS" VALUES (1,'Home',24,300,'Sales','No');
INSERT INTO "CLAIMS" VALUES (2,'Home',41,1200,'IT','No');
INSERT INTO "CLAIMS" VALUES (3,'Home',38,2800,'Sales','Yes');
INSERT INTO "CLAIMS" VALUES (4,'Home',62,6000,'Marketing','No');
INSERT INTO "CLAIMS" VALUES (5,'Home',51,4000,'Sales','No');
INSERT INTO "CLAIMS" VALUES (6,'Travel',33,200,'Sales','No');
INSERT INTO "CLAIMS" VALUES (7,'Travel',46,800,'IT','No');
INSERT INTO "CLAIMS" VALUES (8,'Travel',42,1000,'Marketing','No');
INSERT INTO "CLAIMS" VALUES (9,'Travel',21,900,'Sales','No');
INSERT INTO "CLAIMS" VALUES (10,'Vehicle',44,4000,'IT','No');
INSERT INTO "CLAIMS" VALUES (11,'Vehicle',64,1000,'Sales','Yes');
INSERT INTO "CLAIMS" VALUES (12,'Vehicle',54,900,'IT','No');
INSERT INTO "CLAIMS" VALUES (13,'Vehicle',26,2500,'Sales','No');
INSERT INTO "CLAIMS" VALUES (14,'Vehicle',44,1300,'Marketing','Yes');

INSERT INTO "CLAIMS_MV" VALUES (1,'Home',24,300,'Sales','No');
INSERT INTO "CLAIMS_MV" VALUES (2,'Home',41,1200,'IT','No');
INSERT INTO "CLAIMS_MV" VALUES (3,'Home',38,2800,'Sales','Yes');
INSERT INTO "CLAIMS_MV" VALUES (4,'Home',62,6000,'Marketing','No');
INSERT INTO "CLAIMS_MV" VALUES (5,'Home',51,4000,'Sales','No');
INSERT INTO "CLAIMS_MV" VALUES (6,'Travel',33,200,'Sales','No');
INSERT INTO "CLAIMS_MV" VALUES (7,'Travel',46,800,'IT','No');
INSERT INTO "CLAIMS_MV" VALUES (8,'Travel',42,1000,'Marketing','No');
INSERT INTO "CLAIMS_MV" VALUES (9,'Travel',21,900,'Sales','No');
INSERT INTO "CLAIMS_MV" VALUES (10,null,44,4000,'IT','No');
INSERT INTO "CLAIMS_MV" VALUES (11,null,64,1000,'Sales','Yes');
INSERT INTO "CLAIMS_MV" VALUES (12,'Vehicle',54,900,null,'No');
INSERT INTO "CLAIMS_MV" VALUES (13,'Vehicle',null,2500,'Sales','No');
INSERT INTO "CLAIMS_MV" VALUES (14,'Vehicle',44,null,'Marketing','Yes');

INSERT INTO "FRAUD" VALUES (1,0,1,24,300,1);
INSERT INTO "FRAUD" VALUES (2,0,1,41,1200,2);
INSERT INTO "FRAUD" VALUES (3,1,1,38,2800,1);
INSERT INTO "FRAUD" VALUES (4,0,1,62,6000,3);
INSERT INTO "FRAUD" VALUES (5,0,1,51,4000,1);
INSERT INTO "FRAUD" VALUES (6,0,2,33,200,1);
INSERT INTO "FRAUD" VALUES (7,0,2,46,800,2);
INSERT INTO "FRAUD" VALUES (8,0,2,42,1000,3);
INSERT INTO "FRAUD" VALUES (9,0,2,21,900,1);
INSERT INTO "FRAUD" VALUES (10,0,3,44,4000,2);
INSERT INTO "FRAUD" VALUES (11,1,3,64,1000,1);
INSERT INTO "FRAUD" VALUES (12,0,3,54,900,2);
INSERT INTO "FRAUD" VALUES (13,0,3,26,2500,1);
INSERT INTO "FRAUD" VALUES (14,1,3,44,1300,3);

IMPORT FROM CSV FILE '/tmp/PAL/STOCKS.csv' 
	   INTO "STOCKS" 
       WITH COLUMN LIST IN FIRST ROW RECORD DELIMITED BY '\n' FIELD DELIMITED BY ',' OPTIONALLY ENCLOSED BY '"' ERROR LOG 'STOCKS.err' THREADS 10 BATCH 10000 TABLE LOCK
       ;

INSERT INTO "FAILURES" VALUES (71);
INSERT INTO "FAILURES" VALUES (83);
INSERT INTO "FAILURES" VALUES (92);
INSERT INTO "FAILURES" VALUES (104);
INSERT INTO "FAILURES" VALUES (120);
INSERT INTO "FAILURES" VALUES (134);
INSERT INTO "FAILURES" VALUES (138);
INSERT INTO "FAILURES" VALUES (146);
INSERT INTO "FAILURES" VALUES (181);
INSERT INTO "FAILURES" VALUES (191);
INSERT INTO "FAILURES" VALUES (206);
INSERT INTO "FAILURES" VALUES (226);
INSERT INTO "FAILURES" VALUES (276);
INSERT INTO "FAILURES" VALUES (283);
INSERT INTO "FAILURES" VALUES (291);
INSERT INTO "FAILURES" VALUES (332);
INSERT INTO "FAILURES" VALUES (351);
INSERT INTO "FAILURES" VALUES (401);
INSERT INTO "FAILURES" VALUES (466);

INSERT INTO "FAILURES_CENSORED" VALUES (17, null);
INSERT INTO "FAILURES_CENSORED" VALUES (55, null);
INSERT INTO "FAILURES_CENSORED" VALUES (55, null);
INSERT INTO "FAILURES_CENSORED" VALUES (71, 71);
INSERT INTO "FAILURES_CENSORED" VALUES (83, 83);
INSERT INTO "FAILURES_CENSORED" VALUES (85, null);
INSERT INTO "FAILURES_CENSORED" VALUES (92, 92);
INSERT INTO "FAILURES_CENSORED" VALUES (104, 104);
INSERT INTO "FAILURES_CENSORED" VALUES (115, null);
INSERT INTO "FAILURES_CENSORED" VALUES (120, 120);
INSERT INTO "FAILURES_CENSORED" VALUES (125, null);
INSERT INTO "FAILURES_CENSORED" VALUES (134, 134);
INSERT INTO "FAILURES_CENSORED" VALUES (138, 138);
INSERT INTO "FAILURES_CENSORED" VALUES (146, 146);
INSERT INTO "FAILURES_CENSORED" VALUES (163, null);
INSERT INTO "FAILURES_CENSORED" VALUES (171, null);
INSERT INTO "FAILURES_CENSORED" VALUES (181, 181);
INSERT INTO "FAILURES_CENSORED" VALUES (191, 191);
INSERT INTO "FAILURES_CENSORED" VALUES (195, null);
INSERT INTO "FAILURES_CENSORED" VALUES (206, 206);
INSERT INTO "FAILURES_CENSORED" VALUES (226, 226);
INSERT INTO "FAILURES_CENSORED" VALUES (260, null);
INSERT INTO "FAILURES_CENSORED" VALUES (276, 276);
INSERT INTO "FAILURES_CENSORED" VALUES (283, 283);
INSERT INTO "FAILURES_CENSORED" VALUES (291, 291);
INSERT INTO "FAILURES_CENSORED" VALUES (332, 332);
INSERT INTO "FAILURES_CENSORED" VALUES (351, 351);
INSERT INTO "FAILURES_CENSORED" VALUES (384, null);
INSERT INTO "FAILURES_CENSORED" VALUES (401, 401);
INSERT INTO "FAILURES_CENSORED" VALUES (466, 466);
